### ISSUE TITLE
Possibility to change the favicon

### ISSUE THREAD

**Issue by FirePowi** [Chocobozzz/PeerTube#1043]
* **What is the expected behaviour?**
A guide on how to edit the favicon or an easy way of editing it.

* **What do you see instead?**
The logo of PeerTube

The must would be to change the whole logo at once as in #1215

**Comment by Chocobozzz** [comment]
Ping @fflorent

**Comment by fflorent** [comment]
Well, two answers

### What I did (probably nor the best solution nor easiest solution)

I added this in the `production.yaml`:
```yaml
instance:
  customizations:
    javascript: |
      document.head.querySelector('link[rel="icon"]').href = 'data:image/png;base64,<my base64 png>';
    css: |
      #peertube-title .icon-logo {
        width: 33px !important;
        background: url('data:image/png;base64,<my base64 png>') no-repeat !important;;
      }
```

Where `<my base64 png>` have to be replaced with the result of this command (on unix / linux system):
```bash
$ base64 -w 0 /path/to/file.png
```

It works but the drawback is:
 - well, hackyish;
 - not easy!
 - the favicon of Peertube appears in search engine results instead of your own one;

### What I think is better (needs to be tested)

Try to replace this file: `./client/src/assets/images/favicon.png`

Not tested, but I am quite sure it fixes all the drawbacks above.
