### ISSUE TITLE
Can't connect : "invalid client : client is invalid"

### ISSUE THREAD

**Issue by jadjay** [Chocobozzz/PeerTube#1073]
* **PeerTube version beta9 :**
* **Firefox:**
* **NodeJS 8x:**

* **What is the expected behaviour?** Being able to connect with fresh root login/passwd
* **What do you see instead?** invalid client : client is invalid

* **Browser console log if useful:** None
* **Server log if useful (journalctl or /var/www/peertube/storage/logs):**
Sep 16 13:25:19 peertube2 peertube[16251]: [peertube.rXXXXX.fr:9000] 2018-09-16 13:25:19.282 debug: Getting Client (clientId: null, clientSecret: null).
Sep 16 13:25:19 peertube2 peertube[16251]: [peertube.rXXXXX.fr:9000] 2018-09-16 13:25:19.309 debug: Executing (default): SELECT "id", "clientId", "clientSecret", "grants", "redirectUris", "createdAt", "updatedAt" FROM "oAuthClient" AS "OAuthClientModel" WHERE "OAuthClientModel"."clientId" = 'null' AND "OAuthClientModel"."clientSecret" = 'null' LIMIT 1;
Sep 16 13:25:19 peertube2 peertube[16251]: [peertube.rXXXXX.fr:9000] 2018-09-16 13:25:19.329 info: 192.168.0.0 - - [16/Sep/2018:13:25:19 +0000] "POST /api/v1/users/token HTTP/1.0" 400 69 "https://peertube.rXXXXX.fr/login" "Firefox"

**Comment by jadjay** [comment]
Okay my bad !

Be sure that 
```yaml
  webserver:
    hostname: mypt.mydom.io   # No quote, double quote, bracket or whatsoever
    https: True                            # No quote, double quote, bracket or whatsoever
    port: 443                               # No quote, double quote, bracket or whatsoever
```
