### ISSUE TITLE
Disable/clear watch history

### ISSUE THREAD

**Issue by Chocobozzz** [Chocobozzz/PeerTube#1200]
* [x] Add ability to clear history
 *  [x] Add ability to disable history

**Comment by rigelk** [comment]
Some instance admins will want to disable history by default and leave the activation to the activation to the user, so as to store as little as possible about the user.

**Comment by Chocobozzz** [comment]
:+1: 

We could do like the nsfw policy. In configuration:

```

user:
  # Default value of maximum video BYTES the user can upload (does not take into account transcoded files).
  # -1 == unlimited
  video_quota: -1
  video_quota_daily: -1
  # Is user watch history enabled by default or not
  # Could be overrode by the user preferences
  watch_history:
    enabled: true
```
