### ISSUE TITLE
Domain change with traefik

### ISSUE THREAD

**Issue by sokoow** [Chocobozzz/PeerTube#1257]
I'm trying to run peertube behind a traefik reverse proxy, and gettings this:

```2018-10-13 15:43:08.295 warn: It seems PeerTube was started (and created some data) with another domain name. This means you will not be able to federate! Please use NODE_CONFIG_DIR=/config NODE_ENV=production npm run update-host to fix this.```

I got PEERTUBE_WEBSERVER_HOSTNAME set to my external domain name, and am running traefik with letsencrypt ACME - pod name (hostname that node recognizes) will always differ from the real name.

Can the dockerfile runner be amended to run npm run update-host every time it starts pls ? or am I missing something else ? Cheers

**Comment by Chocobozzz** [comment]
I'm not sure to understand: your domain name changes every time you start the container?

**Comment by sokoow** [comment]
Well, I run on kubernetes behind traefik proxy, so my ingress HTTP traffic looks like following:

Internetz -> traefik ingress proxy -> kubernetes -> pod (docker containers)

now the reverse proxy let's say has a domain pinned to it like peertube.awesome.com, so it gets a HTTP host header like this. Now the problem is that pods (docker containers on kube) have each its unique, randomized hostnames (on the basis of a hash). Therefore I can't figure out why it's restarting all the time after printing a message above.

**Comment by LecygneNoir** [comment]
Hello @sokoow 

On kubernetes, I have this message the first time I start my pod, but only because I migrated the postgres database and videos data from another instances (which indeed had a different hostname).

Once I have launched the update-host one time, it's patched and the error disappears, even when pods restart or is upgraded.

And from fresh instance (for dev purpose) with no video and new databases, I have never seen this error 🤔 
For my part I do not use traeffik, but I don't think it's linked. For what I know about the peertube internal process, this error is printed at the very launch of the pods, before any request are send by traefik, so I tends to think there is something wrong with the config, some existing torrent or the database :)

Are you sure your database and config directories are persistent and not recreated at each launch?
Do you use helm charts to create the pods, or manual deployments?

**Comment by sokoow** [comment]
Thanks for replying, nice to see another kube-head around :) I got a bunch of loose yaml manifests for a moment only, just to prove it's working, that'll get templatized soon. Now, the fact we are discussing this means that obviously the original docker image doesn't do update-host ever, right ? What about rebuilding it so it does on every run ? It shouldn't break existing workflows, and it'll make kubernetes deployment possible.

**Comment by LecygneNoir** [comment]
You're welcome!

Mmmh, I am unsure relaunching at each start a good idea, as the process can take long time (around 5 hours for my instances with all videos for instance). Launching it at each start will consume lot of resources and time :-/

In my setup, I never have to relaunch the update, even if I restart the pod, or update it with new images. I use kubernetes from beta11 from beta16 and now 1.0, the only time I have to launch the update is when I have migrated data from my legacy instance to k8s, and after that Peertube has never complained.

Did the update takes time on your instance? Perhaps it has no time to complete before the ssh connection breaks.
Beware that the docker image has 2 persistent storages, one for the videos/logs/torrent and one for the config. If one is lost when you restart a pod, it could causes the problem?

Again with fresh installation I do not have the problem, so if you install a totally new instance, with a new databases, do you still have this problem?

Are you migrating data from another instance? Or just changing the domains for your existing k8s instance? If we find where is the cause, I am pretty confident we could solve the problem as for me it does'nt exist anymore ;-)

**Comment by sokoow** [comment]
I'm not doing anything fancy, just deploying peertube with this:

```
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  peertube
  labels:
    app: peertube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: peertube
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: peertube
    spec:
      containers:
      - name: redis
        image: "library/redis"
        imagePullPolicy: Always
        ports:
          - name: redis
            containerPort: 6379
            protocol: TCP
      - name: peertube
        image: "chocobozzz/peertube:production-stretch"
        imagePullPolicy: Always
        env:
        - name: PEERTUBE_DB_HOSTNAME
          value: xxx
        - name: PEERTUBE_DB_USERNAME
          value: xxx
        - name: PEERTUBE_DB_PASSWORD
          value: xxx
        - name: PEERTUBE_REDIS_HOSTNAME
          value: peertube-redis-svc
        - name: PEERTUBE_WEBSERVER_HOSTNAME
          value: peertube.xxx
        - name: PEERTUBE_WEBSERVER_PORT
          value: "80"
        - name: PEERTUBE_WEBSERVER_HTTPS
          value: "false"
        ports:
          - name: svc2pod
            containerPort: 9000
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: svc2pod
        readinessProbe:
          httpGet:
            path: /
            port: svc2pod
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
       - name: data
         hostPath:
          path: /data/peertube
---
apiVersion: v1
kind: Service
metadata:
  name: peertube-redis-svc
spec:
  selector:
    app: peertube
  ports:
  - name: redis
    port: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: peertube-svc
spec:
  selector:
    app: peertube
  ports:
  - name: svc2pod
    port: 9000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: peertube
spec:
  rules:
  - host: peertube.xxx
    http:
      paths:
      - path: /
        backend:
          serviceName: peertube-svc
          servicePort: 9000
```

and in peertube logs I got:

```
$ kubectl logs peertube-597d977456-2c2xr peertube

> peertube@1.0.1 start /app
> node dist/server

[peertube.puczat.pl:443] 2018-10-23 16:26:30.044 info: Database peertube is ready.
[peertube.puczat.pl:443] 2018-10-23 16:26:30.521 info: Using xxx:487 as SMTP server.
[peertube.puczat.pl:443] 2018-10-23 16:26:30.529 info: Testing SMTP server...
[peertube.puczat.pl:443] 2018-10-23 16:26:30.588 warn: It seems PeerTube was started (and created some data) with another domain name. This means you will not be able to federate! Please use NODE_CONFIG_DIR=/config NODE_ENV=production npm run update-host to fix this.
```

and it restarts all the time. Obviously kube is running it under a hostname of peertube-597d977456-2c2xr , not peertube.xxx and that might be a problem ?
