### ISSUE TITLE
Not possible to log in fresh install

### ISSUE THREAD

**Issue by romjean** [Chocobozzz/PeerTube#1594]
**What happened?**
After a fresh install on Ubuntu 16.04 with apache web server, I changed the "root" user password with the command given in the tutorial (production.md in this project), then tried to login with user root and modified password, but I've been returned an error "Invalid client: client is invalid".

<img width="622" alt="error_peertube_login" src="https://user-images.githubusercontent.com/15798122/52082587-771d1a80-259d-11e9-9f4f-27b9bc6d54b1.png">

In the logs, I found this:
```
info: Getting client tokens for host localhost:9000 is forbidden (expected sub.domain.fr)
```
Here my config file:
```
listen:
  hostname: 'localhost'
  port: 9000

# Correspond to your reverse proxy server_name/listen configuration
webserver:
  https: true
  hostname: sub.domain.fr #(anonymized)
  port: 443

# Proxies to trust to get real client IP
# If you run PeerTube just behind a local proxy (nginx), keep 'loopback'
# If you run PeerTube behind a remote proxy, add the proxy IP address (or subnet)
trust_proxy:
  - 'loopback'

# Your database name will be "peertube"+database.suffix
database:
  hostname: 'localhost'
  port: 5432
  suffix: '_prod'
  username: user
  password: pass
  pool:
    max: 5

# Redis server for short time storage
# You can also specify a 'socket' path to a unix socket but first need to
# comment out hostname and port
redis:
  hostname: 'localhost'
  port: 6379
  auth: null
  db: 0
```

My apache config
```
<VirtualHost *:443>

        ServerAdmin xxx@xxx.xxx
        ServerName xxx.xxxxxx.xx
        Protocols h2 http/1.1

SSLEngine on
Include /etc/letsencrypt/options-ssl-apache.conf

# Websocket tracker
RewriteEngine On
RewriteCond %{HTTP:Upgrade} websocket [NC]
        RewriteRule /(.*) ws://127.0.0.1:9000/$1 [P,L]

        <Location />
                ProxyPass http://127.0.0.1:9000/
        </Location>

                SSLCertificateFile /etc/letsencrypt/live/domain/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/domain/privkey.pem
</VirtualHost>
</IfModule>
```

**What do you expect to happen instead?**
Login successfull !

**Additional information**
* PeerTube version or URL: 1.1.0
* Browser name/version: Chrome
* NodeJS version: 8.15
