### ISSUE TITLE
Error during systemd setup, Failed to start peertube daemon

### ISSUE THREAD

**Issue by ChanoSan** [Chocobozzz/PeerTube#1739]
First time posting an Issue, also first time installing PeerTube. Apologies in advance for any mistakes on my part, I did try a search for issues beforehand and found nothing that quite matched.

Was following production.md instructions for Peertube, everything went smoothly until systemd setup. After running:
`$ sudo systemctl start peertube`
`$ sudo journalctl -feu peertube`

I'm met with the following error log from journalctl: 
https://pastebin.com/ynvW4ehB

Normally in this situation I figured I'd go to /var/www/peertube/storage/logs/ and check out peertube.log, except in this case neither the logs directory nor the logfile is present, which I found odd.

Everything up until that point worked fine, and followed the dependencies instructions, but I keep getting this error. Thanks in advance for any assistance.

EDIT: sorry, should have mentioned, running on a VPS using Ubuntu 18.04

**Additional information**
* PeerTube version or URL: v1.2.1
* NodeJS version: 10.15.3

* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/): https://pastebin.com/ynvW4ehB [same as above]

**Comment by tcitworld** [comment]
Please paste the `redundancy` section of your config file, you probably have the same issue than #1709

**Comment by ChanoSan** [comment]
This would be from /var/www/peertube/config/production.yaml?
Here it is:
https://pastebin.com/UHSMqKDT

**Comment by tcitworld** [comment]
Same typo, change
```yaml
#      -
        size: '10GB'
        # Minimum time the video must remain in the cache. Only accept values > 10 hours (to not overload remote instances)
        min_lifetime: '48 hours'
        strategy: 'trending' # Cache trending videos
```
in
```yaml
      -
        size: '10GB'
        # Minimum time the video must remain in the cache. Only accept values > 10 hours (to not overload remote instances)
        min_lifetime: '48 hours'
        strategy: 'trending' # Cache trending videos
```
by uncommenting the line with the `-`
