### ISSUE TITLE
Better affordance for support button

### ISSUE THREAD

**Issue by 1000i100** [Chocobozzz/PeerTube#1766]
On ThinkerView instance, there is a small improvement that look georgeous to me : https://thinkerview.video/videos/watch/3a9fae39-92e1-4ee5-bbad-fc1eee902422
```css
div.action-button-support {
    background-color: #45be84 !important;
    color: white !important;
}
div.action-button-support:hover {
    background-color: #61cb98;
    background-color: #d84759 !important;
}
```
Perhaps not the red on hover, but the green saying : it's available, yes you can support us !
It look like a must have to me and should be added by default in my opinon.
