### ISSUE TITLE
Dockerized PeerTube fails to start due to missing environment variables to specify the Redis DB hostname and port

### ISSUE THREAD

**Issue by whalehub** [Chocobozzz/PeerTube#1890]
**What happened?**
I launched the dockerized version of PeerTube with Docker-Compose and encountered an error about the connection to the Redis DB being refused in the PeerTube container's logs. It looks like PeerTube tries to connect to the Redis DB on 127.0.0.1/localhost by default, which differs from the address/hostname that I configured for Redis in my Docker-Compose file.

**What do you expect to happen instead?**
I actually don't expect it to work without specifying the Redis DB's hostname and port, but there are seemingly no environment variables that allow you to do that.

**Steps to reproduce:**
1. Install Docker and Docker-Compose.
2. Run `sudo docker network create proxy --subnet 172.30.0.0/24 --gateway 172.30.0.1` on your server.
3. Save the following text as a docker-compose.yml file.

```yaml
version: "3.7"

services:
  peertube:
    image: chocobozzz/peertube:production-stretch
    container_name: peertube
    hostname: peertube
    restart: unless-stopped
    depends_on:
      - postgres-peertube
      - redis-peertube
    volumes:
      - /mnt/storage/docker/peertube/data:/data
      - /mnt/storage/docker/peertube:/config
    networks:
      proxy:
        ipv4_address: 172.30.0.73
    environment:
      - PEERTUBE_WEBSERVER_HOSTNAME=<redacted>
      - PEERTUBE_WEBSERVER_PORT=80
      - PEERTUBE_WEBSERVER_HTTPS=false
      - PEERTUBE_TRUST_PROXY=["127.0.0.1"]
      - PEERTUBE_SMTP_USERNAME=<redacted>
      - PEERTUBE_SMTP_PASSWORD=<redacted>
      - PEERTUBE_SMTP_HOSTNAME=<redacted>
      - PEERTUBE_SMTP_PORT=587
      - PEERTUBE_SMTP_FROM=<redacted>
      - PEERTUBE_SMTP_TLS=true
      - PEERTUBE_SMTP_DISABLE_STARTTLS=false
      - PEERTUBE_ADMIN_EMAIL=<redacted>
  postgres-peertube:
    image: postgres:10-alpine
    container_name: postgres-peertube
    hostname: postgres-peertube
    restart: unless-stopped
    volumes:
      - /mnt/storage/docker/postgres-peertube:/var/lib/postgresql/data
    networks:
      proxy:
        ipv4_address: 172.30.0.74
    environment:
      - POSTGRES_USER=<redacted>
      - POSTGRES_PASSWORD=<redacted>
      - POSTGRES_DB=<redacted>
  redis-peertube:
    image: redis:4-alpine
    container_name: redis-peertube
    hostname: redis-peertube
    restart: unless-stopped
    volumes:
      - /mnt/storage/docker/redis-peertube:/data
    networks:
      proxy:
        ipv4_address: 172.30.0.75

networks:
  proxy:
    external:
      name: proxy
```
4. Launch PeerTube by running the command `sudo docker-compose up -d`.
5. View the PeerTube container's logs by running the command `sudo docker-compose logs`.

**Additional information**
* PeerTube version or URL: 1.3.0
* Browser name/version: N/A
* NodeJS version: N/A

* Link to browser console log if useful: N/A
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

```
root@debian:~# docker-compose -f /root/docker-compose/peertube.yml logs
Attaching to peertube, postgres-peertube, redis-peertube
peertube             |
peertube             | > peertube@1.3.0 start /app
peertube             | > node dist/server
peertube             |
peertube             | WARNING: NODE_ENV value of 'production' did not match any deployment config file names.
peertube             | WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
peertube             | [<redacted>:80] 2019-06-11 05:40:33.021 warn: Directory of tmp should not be in the production directory of PeerTube. Please check your production configuration file.
peertube             | [<redacted>:80] 2019-06-11 05:40:33.024 warn: Directory of avatars should not be in the production directory of PeerTube. Please check your production configuration file.
peertube             | [<redacted>:80] 2019-06-11 05:40:33.024 warn: Directory of videos should not be in the production directory of PeerTube. Please check your production configuration file.
peertube             | [<redacted>:80] 2019-06-11 05:40:33.024 warn: Directory of streaming_playlists should not be in the production directory of PeerTube. Please check your production configuration file.
peertube             | [<redacted>:80] 2019-06-11 05:40:33.025 warn: Directory of redundancy should not be in the production directory of PeerTube. Please check your production configuration file.
peertube             | [<redacted>:80] 2019-06-11 05:40:33.025 warn: Directory of logs should not be in the production directory of PeerTube. Please check your production configuration file.
peertube             | [<redacted>:80] 2019-06-11 05:40:33.025 warn: Directory of previews should not be in the production directory of PeerTube. Please check your production configuration file.
peertube             | [<redacted>:80] 2019-06-11 05:40:33.026 warn: Directory of thumbnails should not be in the production directory of PeerTube. Please check your production configuration file.
peertube             | [<redacted>:80] 2019-06-11 05:40:33.026 warn: Directory of torrents should not be in the production directory of PeerTube. Please check your production configuration file.
peertube             | [<redacted>:80] 2019-06-11 05:40:33.026 warn: Directory of captions should not be in the production directory of PeerTube. Please check your production configuration file.
peertube             | [<redacted>:80] 2019-06-11 05:40:33.026 warn: Directory of cache should not be in the production directory of PeerTube. Please check your production configuration file.
peertube             | [<redacted>:80] 2019-06-11 05:40:33.441 error: Error in Redis client. {
peertube             |   "err": {
peertube             |     "stack": "Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)",
peertube             |     "message": "Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379",
peertube             |     "errno": "ECONNREFUSED",
peertube             |     "code": "ECONNREFUSED",
peertube             |     "syscall": "connect",
peertube             |     "address": "127.0.0.1",
peertube             |     "port": 6379
peertube             |   }
peertube             | }
peertube             | npm ERR! code ELIFECYCLE
peertube             | npm ERR! errno 255
peertube             | npm ERR! peertube@1.3.0 start: `node dist/server`
peertube             | npm ERR! Exit status 255
peertube             | npm ERR!
peertube             | npm ERR! Failed at the peertube@1.3.0 start script.
peertube             | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
peertube             |
peertube             | npm ERR! A complete log of this run can be found in:
peertube             | npm ERR!     /home/peertube/.npm/_logs/2019-06-11T05_40_33_465Z-debug.log
peertube             |
peertube             | > peertube@1.3.0 start /app
peertube             | > node dist/server
peertube             |
```
