### ISSUE TITLE
Error after changing directory

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#1968]
Hi, I changed the directory to /mnt/peertube/storage... and now the error when adding a torrent. Help fix it?
Сaching in nginx configuration file also fixed
```
storage:
  tmp: '/mnt/peertube/storage/tmp/' 
  avatars: '/mnt/peertube/storage/avatars/'
  videos: '/mnt/peertube/storage/videos/'
  streaming_playlists: '/mnt/peertube/storage/streaming-playlists/'
  redundancy: '/mnt/peertube/storage/videos/'
  logs: '/mnt/peertube/storage/logs/'
  previews: '/mnt/peertube/storage/previews/'
  thumbnails: '/mnt/peertube/storage/thumbnails/'
  torrents: '/mnt/peertube/storage/torrents/'
  captions: '/mnt/peertube/storage/captions/'
  cache: '/mnt/peertube/storage/cache/'
```
```
#root /var/www/peertube/storage;
  root /mnt/peertube/storage;
```

**This torrent file is not supported or too large. Please, make sure it is of the following type: .torrent**

_{"path":"/api/v1/videos/imports/","err":{"torrentfile":{"location":"body","param":"torrentfile","msg":"This torrent file is not supported or too large. Please, make sure it is of the following type: .torrent"}},"level":"warn","message":"Incorrect request parameters","label":"peertube.ustim.ru:443","timestamp":"2019-07-14T11:25:36.575Z"}_
