### ISSUE TITLE
Errors with multiple address

### ISSUE THREAD

**Issue by ne-vlezay80** [Chocobozzz/PeerTube#2033]
**What happened?**
Used multiple address with nginx config.
**What do you expect to happen instead?**
Used peertube with maltiple server address.
**Steps to reproduce:**

1. Create multiple address with nginx.

2. Try play video with Vivaldi 2.7.1628.21

**Additional information**
* PeerTube version or URL: http://www.peertube.ygg/
* Browser name/version: Vivaldi 2.7.1628.21

Please add multiple address support.

**Comment by Chocobozzz** [comment]
You mean load balancing?

**Comment by ne-vlezay80** [comment]
No, the server should avail ip address and domain.

**Comment by JohnXLivingston** [comment]
You can't use multiple domain names because of federation. Each video must have an unique url.

**Comment by Cormoran96** [comment]
Yes, you can and it's work. 
You can use a yaml "hack"

something like that:
```yaml
webserver:
  https: true
  hostname:
   - 'video.domain.net'
   - 'video.domain2.com'
  port: 443
```
