### ISSUE TITLE
502 bad gateway

### ISSUE THREAD

**Issue by stemy2** [Chocobozzz/PeerTube#2084]
**What happened?**
Can't access to my instance because of an error 502
**What do you expect to happen instead?**
Accessing to my instance
**Steps to reproduce:**

1. Go to peertube.stemy.me

2. Problem appears out of the blue.

**Additional information**
* PeerTube version or URL: peertube.stemy.me
* Browser name/version: firefox 68.0.2
* NodeJS version: 4.8.2~dfsg-1

**Comment by JohnXLivingston** [comment]
Is your peertube service running ? 
What is the output of these commands:
- sudo service peertube status
- sudo journalctl -feu peertube

**Comment by stemy2** [comment]
I uninstalled the app and i wasn't able to reinstall it because of its inability to access to postgresql. So i restarted pgsql and it unlocked everything. I still don't know why pgsql stopped.

**Comment by stemy2** [comment]
I was wrong, peertube is still not working. The service is active, but i think i saw some errors in journalctl. Here is a short extract (i had to stop the command cause it was going on and on): https://stemy.me/zerobin/?e259f4916d131c82#9abYWKWgeyoJmd3hBzBJBBjt8qjnEfdMxFC+mzvgt7g=

**Comment by frankstrater** [comment]
I recognize this error, because I have seen it before when I installed PeerTube for the first time. In my case I forgot to update the PostgreSQL password in the production.yaml configuration file. Could you check if you have entered the same password which you chose during install for the peertube PostgreSQL user? See below for the specific part in the YAML file:

```yaml
# Your database name will be "peertube"+database.suffix
database:
  hostname: 'localhost'
  port: 5432
  suffix: '_prod'
  username: 'peertube'
  password: 'peertube'
  pool:
    max: 5
```
