### ISSUE TITLE
prune-storage.js fail because multiple storage keys.

### ISSUE THREAD

**Issue by maxdrash** [Chocobozzz/PeerTube#2128]
**What happened?**
Using the CLI tool: prune-storage.js

**What do you expect to happen instead?**
To prune the storage but fail.

**Steps to reproduce:**

1. Run: systemctl stop peertube && sudo -u peertube NODE_CONFIG_DIR=/var/www/peertube/config NODE_ENV=production npm run prune-storage

2. Get this result:

> peertube@1.4.1 prune-storage /var/www/peertube/versions/peertube-v1.4.1
> node ./dist/scripts/prune-storage.js

Cannot prune storage because you put multiple storage keys in the same directory.

Can you explain why ?
Thanks.

**Additional information**
* PeerTube version or URL: 1.4.1
* NodeJS version: v10.15.2

**Comment by Findus23** [comment]
I think this error means that every one of the storage keys needs to be in another directory for the tool to work. Like e.g.:

```yaml
storage:
  tmp: '/var/www/peertube/storage/tmp/'
  avatars: '/var/www/peertube/storage/avatars/'
  videos: '/var/www/peertube/storage/videos/'
  redundancy: '/var/www/peertube/storage/redundancy/'
  streaming_playlists: '/var/www/peertube/storage/streaming-playlists/'
  logs: '/var/www/peertube/storage/logs/'
  previews: '/var/www/peertube/storage/previews/'
  thumbnails: '/var/www/peertube/storage/thumbnails/'
  torrents: '/var/www/peertube/storage/torrents/'
  captions: '/var/www/peertube/storage/captions/'
  cache: '/var/www/peertube/storage/cache/'
```
