### ISSUE TITLE
403 error when trying to follow peerTube user from pherephone

### ISSUE THREAD

**Issue by qwazix** [Chocobozzz/PeerTube#2197]
I am building [pherephone](https://github.com/writeas/pherephone) which is an *activityPub* repeater and I'm trying to make it work with as many AP implementations as possible.

**What happened?**
I am issuing the following follow request

``` yaml
Accept: application/activity+json; charset=utf-8
Accept-Charset: utf-8
Content-Type: application/activity+json; charset=utf-8
Date: Tue, 22 Oct 2019 07:36:32 GMT
Digest: SHA-256=K8g3os6T/GR0NOeMCS9yqc15eU5u2999Lr9DYJ9Jloo=
Host: pe.ertu.be
Signature: keyId="https://floorb.qwazix.com/myAwesomeList5#main-key",algorithm="rsa-sha256",headers="(request-target) date host digest",signature="OS0ydgE3fnM77csS4oNQj6XmD5+REsTgxk/24WMKsF5h5Qp3mWHdWH7EBVFfdy8AdC8sz5Oper8heK5dt8j+U1yaF8mM0uL2NlGncRtLsZxHUy2VtZy45XeuH9qgrMVSwTGqAHYDLlWBhPVO2SW5CJ+I/8ALpBLo8vr1BqwrbOZqV4eqwT87KrZm9PvzDJZVARRp1lMDPoeCo2cd9XT3kaGWyNL5Nhmi+uTJ9NIbcvtNY+RbcYljCs7ztC6RppEc5jEBOyvYK8xlQOg36ZZjH4ZknDMd0QacLkE9SYxagm916obZ9sDfMPD+HJjuOzwq5DfIT0gezQIxyDgxk8F85g=="
User-Agent: pherephone 0.99
```

``` json
 {
        "@context": [
                "https://www.w3.org/ns/activitystreams"
        ],
        "actor": "https://floorb.qwazix.com/myAwesomeList5",
        "id": "https://floorb.qwazix.com/myAwesomeList5/item/1YPm8w03xfTbfhtb",
        "object": "https://pe.ertu.be/accounts/qwazix",
        "type": "Follow"
} 
```

*PeerTube* responds with `403 Forbidden`

**What do you expect to happen instead?**

Return an `Accept` activity. Pixelfed, mastodon, writefreely and pleroma all accept these follow requests.

Any pointers on what PeerTube expects to be done differently?
