### ISSUE TITLE
Suggestion: New Cache strategy "Mirror"

### ISSUE THREAD

**Issue by tilllt** [Chocobozzz/PeerTube#2336]
Some words about my setup: i have a docker instance of peertube running on my homeserver with a medium speed uplink. I convinced a friend to spin up a peertube instance and i rented a cheapo VPS instance to  accumulate the bandwidth for a proper viewing experience, even in higher quality videos.

Our little peertube network is more like an archive than a constantly changing video platform, so the existing caching mechanisms ('most-views' | 'trending' | 'recently-added') dont work for me. What i want is that every instance is a complete mirror of the network, so no matter how old or little watched a video is, it will still be streamed by all participating instances. 

I dont see why a "mirror" strategy would be a problem on the peertube network, if each admin can opt-in or opt-out in being a mirror for another instance...

In the meanwhile, a question about a workaround: is there some other strategy how i can make this work, like rsyncing all stuff from one instance to another?

cheers!

see also this comment, which is basically mentioning the same idea:
https://github.com/Chocobozzz/PeerTube/issues/123#issuecomment-422253155

**Comment by WonderingDane** [comment]
You can use "recently-added" and set the view count to 0?

**Comment by Chocobozzz** [comment]
Yes, I think that should work

**Comment by tilllt** [comment]
I would like to reopen this, since the suggested workaround does not work as expected (for me)

https://www.pixelscope.de/
should be mirrored ENTIRELY by 

https://three.pixelscope.de/

which as you can see, it is not. there are a lot more videos on pixelscope.de than on three.pixelscope.de and latter host still has a lot of free disk space, so thats not the issue. i am using the proposed redundancy strategy.

```
redundancy:
  videos:
    check_interval: '10 minutes'
    strategies:
        -
          size: '25000MB'
          min_lifetime: '14 days'
          strategy: 'recently-added'
          min_views: 0
```
