### ISSUE TITLE
Cannot run local tests 

### ISSUE THREAD

**Issue by kimsible** [Chocobozzz/PeerTube#3022]
It was an old issue, it's more a doc update for a docker-compose dev env with tests.

After following the documentation https://docs.joinpeertube.org/#/contribute-getting-started?id=develop.

I was able to adapt to test env with a docker database and redis containers.

1. Redis tools installation : `sudo  apt install redis-tools`

2. docker-compose.yml dev configuration
```
version: "3.3"

services:

  postgres:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=peertube_dev
      - POSTGRES_USER=peertube
      - POSTGRES_PASSWORD=peertube
    volumes:
      - ../PeerTube/docker-volume/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:4-alpine
    volumes:
      - ../PeerTube/docker-volume/redis:/data
    ports:
      - "6379:6379"
    restart: "always"

networks:
  default:
    ipam:
      driver: default
      config:
      - subnet:  172.18.0.0/16
```

3. I run `docker-compose up -d` in docker compose dev directory

**Federation tests**

I created the 3 databases for test, still in docker compose dev directory : 
```
docker-compose exec -T postgres createdb -U peertube -O peertube peertube_test{1,2,3}
```

**Unit tests**
in docker compose dev directory : 
```
docker-compose exec -T postgres createuser -U peertube --createdb --superuser
```

In PeerTube directory, I run `yarn install`, `npm run build -- --light-fr` and `npm run clean:server:test`

- `npm run test` I got this error : `Error: Module did not self-register.` just after sass-lint 
- for single test unit  (`npm run mocha -- --exit -r ts-node/register -r tsconfig-paths/register --bail server/tests/api/index.ts`) : 
```
TSError: ⨯ Unable to compile TypeScript:
server/helpers/express-utils.ts:121:10 - error TS2367: This condition will always return 'true' since the types 'string | string[] | ParsedQs | ParsedQs[]' and 'boolean' have no overlap.

121   return req.query.skipCount !== true
```

**Node and NPM version**
node v12.18.2 
npm v6.14.5
