### ISSUE TITLE
wrong public ip and p2p isn't working

### ISSUE THREAD

**Issue by kevtechXx** [Chocobozzz/PeerTube#3071]
peertube is showing me the wrong public ip (its showing me the ip of my router 192.168.5.1) and p2p dosn't work too.

my config.yaml:
```
listen:
  hostname: 0.0.0.0
  port: 9000

# Correspond to your reverse proxy server_name/listen configuration
webserver:
  https: true
  hostname: 'kevtechxx.de'
  port: 443

rates_limit:
  api:
    # 50 attempts in 10 seconds
    window: 10 seconds
    max: 50
  login:
    # 15 attempts in 5 min
    window: 5 minutes
    max: 15
  signup:
    # 2 attempts in 5 min (only succeeded attempts are taken into account)
    window: 5 minutes
    max: 2
  ask_send_email:
    # 3 attempts in 5 min
    window: 5 minutes
    max: 3

# Proxies to trust to get real client IP
# If you run PeerTube just behind a local proxy (nginx), keep 'loopback'
# If you run PeerTube behind a remote proxy, add the proxy IP address (or subnet)
trust_proxy:
  - 'loopback'
  - 192.168.5.181
  - 192.168.5.1
```

my nginx configuration:
```
server { listen 80; listen [::]:80; server_name kevtechxx.de; access_log /var/log/nginx/kevtechxx.de.access.log; error_log 
  /var/log/nginx/kevtechxx.de.error.log;
  #location /.well-known/acme-challenge/ { default_type "text/plain"; root /var/www/certbot;
  #}
  location / { return 301 https://$host$request_uri; }
}
server { listen 443 ssl http2; listen [::]:443 ssl http2; server_name kevtechxx.de;
  # For example with certbot (you need a certificate to run https)
  ssl_certificate /etc/letsencrypt/live/kevtechxx.de/fullchain.pem; ssl_certificate_key /etc/letsencrypt/live/kevtechxx.de/privkey.pem;
  # Security hardening (as of 11/02/2018)
  ssl_protocols TLSv1.3; # TLSv1.3, TLSv1.2 if nginx >= 1.13.0 ssl_prefer_server_ciphers on;
  # Remove ECDHE-RSA-AES256-SHA if you don't want compatibility with Android 4
  ssl_ciphers 
  'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA';
  # ssl_ecdh_curve secp384r1; # Requires nginx >= 1.1.0, not compatible with import-videos script dhparam / diffie helman
  ssl_dhparam /etc/ssl/certs/dhparam.pem; ssl_session_timeout 10m; ssl_session_cache shared:SSL:10m; ssl_session_tickets off; # Requires nginx >= 1.5.9 
  ssl_stapling on; # Requires nginx >= 1.3.7 ssl_stapling_verify on; # Requires nginx => 1.3.7
  # HSTS (https://hstspreload.org), requires to be copied in 'location' sections that have add_header directives add_header Strict-Transport-Security 
  #"max-age=63072000; includeSubDomains";
  # Configure with your resolvers resolver $DNS-IP-1 $DNS-IP-2 valid=300s; resolver_timeout 5s;
  resolver 1.1.1.1 1.0.0.1 valid=300s; resolver_timeout 5s;
  # Enable compression for JS/CSS/HTML bundle, for improved client load times. It might be nice to compress JSON, but leaving that out to protect against 
  # potential compression+encryption information leak attacks like BREACH.
  gzip on; gzip_types text/css application/javascript; gzip_vary on;
  # If you have a small /var/lib partition, it could be interesting to store temp nginx uploads in a different place See 
  # https://nginx.org/en/docs/http/ngx_http_core_module.html#client_body_temp_path client_body_temp_path /var/www/peertube/storage/nginx/;
  access_log /var/log/nginx/kevtechxx.de.access.log; error_log /var/log/nginx/kevtechxx.de.error.log;
  #location ^~ '/.well-known/acme-challenge' { default_type "text/plain"; root /var/www/certbot;
  #}
  location / { 
#	proxy_pass http://192.168.5.176:9000; 
	proxy_set_header X-Real-IP $remote_addr; 
	proxy_set_header Host $host; 
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    
    
    # This is the maximum upload size, which roughly matches the maximum size of a video file you can send via the API or the web interface. By default 
    # this is 8GB, but administrators can increase or decrease the limit. Currently there's no way to communicate this limit to users automatically, so you 
    # may want to leave a note in your instance 'about' page if you change this.
    #
    # Note that temporary space is needed equal to the total size of all concurrent uploads. This data gets stored in /var/lib/nginx by default, so you may 
    # want to put this directory on a dedicated filesystem.
    #
    client_max_body_size 8G; proxy_connect_timeout 600; proxy_send_timeout 600; proxy_read_timeout 600; send_timeout 600;
    proxy_pass http://192.168.5.176:9000;
  }
}
```

pls help
