### ISSUE TITLE
Traefik reverse-proxy fatal Unknown entrypoint \"\" for ACME configuration

### ISSUE THREAD

**Issue by Cyrille37** [Chocobozzz/PeerTube#3501]
**Describe the problem**

While running docker-compose there are errors : 
```
reverse-proxy_1  | time="2020-12-21T04:18:51Z" level=fatal msg="Unknown entrypoint \"\" for ACME configuration"
peertube_reverse-proxy_1 exited with code 1
reverse-proxy_1  | time="2020-12-21T04:19:51Z" level=fatal msg="Unknown entrypoint \"\" for ACME configuration"
peertube_reverse-proxy_1 exited with code 1
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**

```
$ curl https://raw.githubusercontent.com/chocobozzz/PeerTube/master/support/docker/production/docker-compose.yml > docker-compose.yml
$ curl https://raw.githubusercontent.com/Chocobozzz/PeerTube/master/support/docker/production/.env > .env
$ nano .env
# add user, password, domain, email ...
$ docker-compose up
```

**Additional information**

* docker-compose version 1.25.0
* PeerTube instance:
  * version: docker

**Comment by Cyrille37** [comment]
I can resolve this with more lines in `traefik` service definition. I do not know if all new lines are mandatory, but it works :-)

```
  reverse-proxy:
    image: traefik:v1.7
    network_mode: "host"
    command:
      - "--docker" # Tells Træfik to listen to docker
      - "--acme.email=${TRAEFIK_ACME_EMAIL}" # Let's Encrypt ACME email
      - "--acme.domains=${TRAEFIK_ACME_DOMAINS}" # Let's Encrypt ACME domain list
      - "--entrypoints=Name:http Address::80 Redirect.EntryPoint:https"
      - "--entrypoints=Name:https Address::443 TLS"
      - "--defaultentrypoints=http,https"
      - "--acme.entrypoint=https"
      - "--acme.httpchallenge"
      - "--acme.httpchallenge.entrypoint=http"
      - "--acme.storage=/acme/acme.json"
    ports:
      - "80:80"     # The HTTP port
      - "443:443"   # The HTTPS port
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # So that Traefik can listen to the Docker events
      #- ./docker-volume/traefik/acme.json:/etc/acme.json
      #- ./docker-volume/traefik/traefik.toml:/traefik.toml
      - ./docker-volume/traefik/:/acme
```
