### ISSUE TITLE
PeerTube cannot send e-mails using the sendmail method

### ISSUE THREAD

**Issue by pietsch** [Chocobozzz/PeerTube#3640]
I configured a fresh PeerTube instance to send out e-mails via the sendmail method. However, it warns me on startup that it cannot send e-mails.

Error messages in syslog:
```
2021-01-25 18:36:38.246 warn: Emailer is disabled so the contact form will not work.
2021-01-25 18:36:39.195 error: Cannot use SMTP server because of lack of configuration. PeerTube will not be able to send mails!
```

Indeed, it does not send e-mails. Error messages in syslog:
```json
"err": {
     "stack": "Error: Cannot send mail because SMTP is not configured.\n    at Emailer.<anonymous> (/var/www/peertube/versions/peertube-v3.0.1/dist/server/lib/emailer.js:498:23)\n    at Generator.next (<anonymous>)\n    at /var/www/peertube/versions/peertube-v3.0.1/node_modules/tslib/tslib.js:114:75\n    at new Promise (<anonymous>)\n    at Object.__awaiter (/var/www/peertube/versions/peertube-v3.0.1/node_modules/tslib/tslib.js:110:16)\n    at Emailer.sendMail (/var/www/peertube/versions/peertube-v3.0.1/dist/server/lib/emailer.js:496:24)\n    at Queue.<anonymous> (/var/www/peertube/versions/peertube-v3.0.1/dist/server/lib/job-queue/handlers/email.js:11:43)\n    at Generator.next (<anonymous>)\n    at /var/www/peertube/versions/peertube-v3.0.1/node_modules/tslib/tslib.js:114:75\n    at new Promise (<anonymous>)\n    at Object.__awaiter (/var/www/peertube/versions/peertube-v3.0.1/node_modules/tslib/tslib.js:110:16)\n    at Queue.processEmail (/var/www/peertube/versions/peertube-v3.0.1/dist/server/lib/job-queue/handlers/email.js:8:20)\n    at handlers.(anonymous function) (/var/www/peertube/versions/peertube-v3.0.1/node_modules/bull/lib/queue.js:656:42)\n    at Queue.processJob (/var/www/peertube/versions/peertube-v3.0.1/node_modules/bull/lib/queue.js:1087:22)\n    at process._tickCallback (internal/process/next_tick.js:68:7)",
     "message": "Cannot send mail because SMTP is not configured."
}
```
Here is the relevant snippet from `/var/www/peertube/config/production.yaml`:
```yaml

smtp:
  # smtp or sendmail
  transport: sendmail
  # Path to sendmail command. Required if you use sendmail transport
  sendmail: /usr/sbin/sendmail
  hostname: null
  port: 465 # If you use StartTLS: 587
  username: null
  password: null
  tls: true # If you use StartTLS: false
  disable_starttls: false
  ca_file: null # Used for self signed certificates
  from_address: 'peertube@REDACTED'
```

Is the sendmail method supported at all? I use Debian's `nullmailer` package to provide `/usr/sbin/sendmail`.

I verified that my sendmail is working by sending out an e-mail using `mailx` on the command line.

* PeerTube instance:
  * version: 3.0.1
  * NodeJS version: 10.23.1\~dfsg-1\~deb10u1
  * Ffmpeg version: 7:4.1.6-1\~deb10u1
