### ISSUE TITLE
Add a Prometheus Exporter

### ISSUE THREAD

**Issue by pichouk** [Chocobozzz/PeerTube#3742]
Hi,

we are hosting a Peertube instance for our association and we kinda like the statistics shown on `/about/instance` page ([this component](https://github.com/Chocobozzz/PeerTube/blob/master/client/src/app/shared/shared-instance/instance-statistics.component.html)) : number of videos, view, etc.

I think it would be nice to have a [Prometheus](https://prometheus.io/) endpoint under `/metrics` to be able to scrape those metrics using Prometheus.
IMHO Prometheus is the leading metrics-scrapping solution and integrate an Prometheus endpoint in Peertube is a feature that can be useful for several organizations hosting Peertube. 

First, I am opening this issue to discuss about the feature. Do you think it could be a good idea to add a Prometheus endpoint to Peertube ?
Second, here is how I imagine this feature : 
- **disabled by default**
- expose metrics under `/metrics` with [Prometheus format](https://prometheus.io/docs/instrumenting/exposition_formats/)
- do not implement any kind of authentication mechanism, just expose the metrics
- at the beginning it will only expose [existing statistics](https://github.com/Chocobozzz/PeerTube/blob/master/shared/models/server/server-stats.model.ts)

I am not really a developer, but I can try to implement the feature. I will probably need help to do it correctly, but I can try :)

What do you think ?

**Comment by Chocobozzz** [comment]
Hello,

I don't want to maintain specific endpoints for every monitoring system. Prometheus does not support JSON input? At Framasoft we just use the REST API using telegraf to graph instance stats: https://peertube2.cpy.re/api/v1/server/stats

**Comment by pichouk** [comment]
Sorry I didn't know that those statistics where available under `/api/v1/server/stats` easily.
I would have prefer to have a Prometheus format, but I agree that this is not a good idea to maintain several monitoring systems integrations. This endpoint can be use to convert metrics to Prometheus format with a little script, I'll do that.

Thanks :)

**Comment by faust64** [comment]
As I was looking for a Prometheus exporter as well.

Based on previous replies, I tried the Prometheus (community) JSON Exporter -- quay.io/prometheuscommunity/json-exporter

Here's a sample configuration, gathering metrics from PeerTube:

```
metrics:
- name: peertube_local_videos_count
  path: "{ .totalLocalVideos }"
  help: Peertube Local Videos Count
- name: peertube_local_video_views_count
  path: "{ .totalLocalVideoViews }"
  help: Peertube Local Video Views
- name: peertube_local_video_size_bytes
  path: "{ .totalLocalVideoFilesSize }"
  help: Peertube Local Video Files Size
- name: peertube_local_video_comments_count
  path: "{ .totalLocalVideoComments }"
  help: Peertube Local Comments Count
- name: peertube_all_videos_count
  path: "{ .totalVideos }"
  help: Peertube Videos Count
- name: peertube_all_video_comments_count
  path: "{ .totalVideoComments }"
  help: Peertube Comments Count
- name: peertube_users_count
  path: "{ .totalUsers }"
  help: Peertube Users Count
- name: peertube_daily_active_users_count
  path: "{ .totalDailyActiveUsers }"
  help: Peertube Active Users Count - last 24h
- name: peertube_weekly_active_users_count
  path: "{ .totalWeeklyActiveUsers }"
  help: Peertube Active Users Count - last 7d
- name: peertube_monthly_active_users_count
  path: "{ .totalMonthlyActiveUsers }"
  help: Peertube Active Users Count - last 30d
- name: peertube_followers_count
  path: "{ .totalInstanceFollowers }"
  help: Peertube Instances Followers Count
- name: peertube_following_count
  path: "{ .totalInstanceFollowing }"
  help: Peertube Instances Following Count
- name: peertube_pub_processed_count
  path: "{ .totalActivityPubMessagesProcessed }"
  help: Peertube Activity Pub Messages Processed Count
- name: peertube_pub_processed_per_sec_avg
  path: "{ .activityPubMessagesProcessedPerSecond }"
  help: Peertube Activity Pub Messages Processed Per Second
- name: peertube_pub_waiting_count
  path: "{ .totalActivityPubMessagesWaiting }"
  help: Peertube Activity Pub Messages Waiting Count
```

Now, the JSON exporter needs a target to be passed, as a GET param, when Prometheus queries your exporter to scrape metrics. Working with Kubernetes, I'ld rather try to avoid any probe with params, as it requires a corresponding configuration in your Prometheus server...  Writing a PeerTube exporter from scratch was easier:

https://gitlab.com/synacksynack/opsperator/docker-peertubeexporter/-/blob/master/config/peertube_exporter.py


```
#!/usr/bin/env python

import os

if os.environ.get('EXPORTER_PORT') is not None:
    bind_port = os.environ.get('EXPORTER_PORT')
else:
    bind_port = 9113
if os.environ.get('PEERTUBE_URL') is not None:
    peertube_root = os.environ.get('PEERTUBE_URL')
else:
    peertube_root = 'http://localhost:9000'
if os.environ.get('DEBUG') is not None:
    do_debug = True
else:
    do_debug = False

peertube_url = peertube_root + '/api/v1/server/stats'

import json
import requests
import sys
import time

from prometheus_client import start_http_server
from prometheus_client.core import GaugeMetricFamily, CounterMetricFamily, REGISTRY

class JSONCollector(object):
    def collect(self):
        response = json.loads(requests.get(peertube_url).content.decode('UTF-8'))

        if do_debug:
            print(dfbytes)
        yield GaugeMetricFamily('peertube_local_videos_count',
                                'Peertube Local Videos Count',
                                int(response['totalLocalVideos']))
        yield GaugeMetricFamily('peertube_local_video_views_count',
                                'Peertube Local Videos Views',
                                int(response['totalLocalVideoViews']))
        yield GaugeMetricFamily('peertube_local_video_size_bytes',
                                'Peertube Local Videos Space Used in Bytes',
                                int(response['totalLocalVideoFilesSize']))
        yield GaugeMetricFamily('peertube_local_video_comments_count',
                                'Peertube Local Videos Comments Count',
                                int(response['totalLocalVideoComments']))
        yield GaugeMetricFamily('peertube_all_videos_count',
                                'Peertube Total Videos Count',
                                int(response['totalVideos']))
        yield GaugeMetricFamily('peertube_all_video_comments_count',
                                'Peertube Total Videos Comments Count',
                                int(response['totalVideoComments']))
        yield GaugeMetricFamily('peertube_users_count',
                                'Peertube Total Users Count',
                                int(response['totalUsers']))
        yield GaugeMetricFamily('peertube_active_users_daily_count',
                                'Peertube Total Users Active in the last day',
                                int(response['totalDailyActiveUsers']))
        yield GaugeMetricFamily('peertube_active_users_weekly_count',
                                'Peertube Total Users Active in the last week',
                                int(response['totalWeeklyActiveUsers']))
        yield GaugeMetricFamily('peertube_active_users_monthly_count',
                                'Peertube Total Users Active in the last month',
                                int(response['totalMonthlyActiveUsers']))
        yield GaugeMetricFamily('peertube_followers_count',
                                'Peertube Followers Instances Count',
                                int(response['totalInstanceFollowers']))
        yield GaugeMetricFamily('peertube_following_count',
                                'Peertube Following Instances Count',
                                int(response['totalInstanceFollowing']))
        yield GaugeMetricFamily('peertube_pub_processed_count',
                                'Peertube Processed Publications Count',
                                int(response['totalActivityPubMessagesProcessed']))
        yield GaugeMetricFamily('peertube_pub_processed_per_sec_avg',
                                'Peertube Average Publications Processed per Second',
                                int(response['activityPubMessagesProcessedPerSecond']))
        yield GaugeMetricFamily('peertube_pub_waiting_count',
                                'Peertube Waiting Publications Count',
                                int(response['totalActivityPubMessagesWaiting']))

if __name__ == "__main__":
    REGISTRY.register(JSONCollector())
    start_http_server(int(bind_port))
    print("Exporter started - listening on :%s" % bind_port)
    while True:
        time.sleep(1)
```

Just make sure to `pip install request` and `prometheus_client`.

**Comment by drym3r** [comment]
@faust64 FYI if you use the [json-exporter](https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-json-exporter) helm chart, it's not really necessary, since it can create the serviceMonitor and it doesn't have any special needs:

```yaml
...
serviceMonitor:
  enabled: true
  defaults:
    labels:
     # The label that your prometheus search on the serviceMonitors
      release: prometheus
  targets:
    - name: whatever
      url: https://whatever.com/api/v1/server/stats
      interval: 60s
      scrapeTimeout: 60s
      additionalMetricsRelabels: {}
...
```
