### ISSUE TITLE
3.1.0 transcoded videos will not play

### ISSUE THREAD

**Issue by SimplyCorbett** [Chocobozzz/PeerTube#3973]
Setup a new instance and my transcoded videos do not play.

![firefox_CXr2DTnD3e](https://user-images.githubusercontent.com/7935624/115104855-1a08a780-9f10-11eb-9444-7ea6687556f8.png)

![firefox_GtiFVTdsHj](https://user-images.githubusercontent.com/7935624/115104818-d6ae3900-9f0f-11eb-9e73-1c1174d2fa94.png)

![firefox_JzwK6mEyHh](https://user-images.githubusercontent.com/7935624/115104840-f7768e80-9f0f-11eb-8bb8-cb65c1665112.png)

Imported URL: https://www.youtube.com/watch?v=rG6nzrksbPQ

* PeerTube instance:
  * version: 3.1.0
  * NodeJS version: 15
  * Ffmpeg version: 4.4
  * Postgresql version: 13
  * Nginx mainline + letsencrypt setup with the config example provided by peertube

* Browser name, version and platforms on which you could reproduce the bug: Edge & Firefox (latest)
```
  # Generate videos in a WebTorrent format (what we do since the first PeerTube release)
  # If you also enabled the hls format, it will multiply videos storage by 2
  # If disabled, breaks federation with PeerTube instances < 2.1
  webtorrent:
    enabled: false

  # /!\ Requires ffmpeg >= 4.1
  # Generate HLS playlists and fragmented MP4 files. Better playback than with WebTorrent:
  #     * Resolution change is smoother
  #     * Faster playback in particular with long videos
  #     * More stable playback (less bugs/infinite loading)
  # If you also enabled the webtorrent format, it will multiply videos storage by 2
  hls:
    enabled: true
```
