### ISSUE TITLE
Add curl package to Dockerfile.buster to allow for healthchecks (swarm, k8s, etc.)

### ISSUE THREAD

**Issue by decentral1se** [Chocobozzz/PeerTube#4045]
**Describe the problem to be solved**

With docker swarm configs, you typically see a thing like this:

```yaml
    healthcheck:
      test: ["cmd", "curl", "-f", "http://localhost:9000"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 10s
```

This allows swarm to understand when containers are healthy and do zero downtime deploys.

Curl appears to be missing from the default image published.

**Describe the solution you would like:**

Let's install curl in the default docker images.

**Describe alternatives you have considered**  

Wget isn't there either, so it seems we're missing that approach.
