### ISSUE TITLE
Redundancy 'Used' size larger than maximum and keeps growing

### ISSUE THREAD

**Issue by GidiKroon** [Chocobozzz/PeerTube#4116]
**Describe the current behaviour**
On my server, the size for the redundancy strategy "recently-added" is set to 5GB in production.yaml. The Used size reported in the Administration page of PeerTube is 14.4GB. The Available space is reported as a negative number.  Each check interval, for me that's twice a day, a new video is added and the used storage grows.

**Steps that may have caused this:**

1. Configure only one strategy, e.g. "recently-added" and set the size to 10GB
2. Wait for this storage to fill up over several days
3. Change the configuration so now two strategies are used ("recently-added" and "trending") and set both to 5GB. Restart.
4. Note that now more storage is used for the "recently-added" strategy than the maximum and that the reported Available space in the pie chart is negative. This is to be expected.
5. Note after several days however that instead of shrinking, the Used space in that category keeps growing.

It is possible that other steps have triggered the bug. However, I know I have done the above steps, though I have only recently noticed point 5, i.e. that it kept increasing. I have not tried to reproduce it by doing this a second time, not willing to mess up the server even more.

**Describe the expected behaviour**

If the current size in a strategy is larger than the configured maximum after a restart, I expect that PeerTube either:

- expires videos immediately to get the Used size below the maximum, or:
- let videos expire at their scheduled times during each check_interval and not take in new videos until the Available space is no longer negative

**Additional information**

The redundancy configuration in production.yaml:

```yaml
# Cache remote videos on your server, to help other instances to broadcast the video
# You can define multiple caches using different sizes/strategies
# Once you have defined your strategies, choose which instances you want to cache in admin -> manage follows -> following
redundancy:
  videos:
    check_interval: '12 hour' # How often you want to check new videos to cache
    strategies: # Just uncomment strategies you want
#      -
#        size: '10GB'
#        # Minimum time the video must remain in the cache. Only accept values > 10 hours (to not overload remote instances)
#        min_lifetime: '48 hours'
#        strategy: 'most-views' # Cache videos that have the most views
      -
        size: '5GB'
        # Minimum time the video must remain in the cache. Only accept values > 10 hours (to not overload remote instances)
        min_lifetime: '48 hours'
        strategy: 'trending' # Cache trending videos
      -
        size: '5GB'
        # Minimum time the video must remain in the cache. Only accept values > 10 hours (to not overload remote instances)
        min_lifetime: '48 hours'
        strategy: 'recently-added' # Cache recently added videos
        min_views: 10 # Having at least x views
```

* PeerTube instance:
  * URL: https://peertube.gidikroon.eu/
  * version: 3.1.0
  * NodeJS version: v12.22.1
  * Ffmpeg version: 4.1.6-1~deb10u1

* Browser name, version and platforms on which you could reproduce the bug: Chome on Android, Firefox on Ubuntu
* Link to browser console log if relevant: n/a
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`): n/a
