### ISSUE TITLE
Background highlight on the hover in left menu

### ISSUE THREAD

**Issue by PhieF** [Chocobozzz/PeerTube#418]
* **PeerTube version or URL:** beta 1
* **Browser name/version:**
* **NodeJS version:**

Left menu should have a hover background, as well as top-left icon
for the left menu, I've successfully "fixed" it by adding 

```css

menu[_ngcontent-c2] .panel-block[_ngcontent-c2] a[_ngcontent-c2]{
height:100%;
line-height:40px;
padding-left: 26px;
display:block;
}
menu[_ngcontent-c2] .block-title[_ngcontent-c2] {
padding-left: 26px
}
menu[_ngcontent-c2] .panel-block[_ngcontent-c2] a[_ngcontent-c2]:hover {
background:var(  --less-dark-blue);
}
```

in css
here is what I get 

https://framapic.org/j0PYJBfACWEw/KumBKRbzF2LP.png

it's better on mobile phone, even if not perfect (a slide animation for the menu would make things smoother, but can be laggy)

Thanks ! :) :)
