### ISSUE TITLE
Video not found after transcoding

### ISSUE THREAD

**Issue by verymilan** [Chocobozzz/PeerTube#4260]
Hi there, i have just noticed, that every now and then, after transcoding is finished, PeerTube can't find the file to copy over.
This is odd, as the affected files (and paths) exist - at least when i give it a look. 

The tmp dir is on the machine itself, the target one however is on network storage... but as i read it, the source can't be found (right?).

````


Job: 12506 Type: video-transcoding Processed on Jul 18, 2021, 5:56:49 PM Finished on Jul 18, 2021, 5:56:54 PM
--
{   "type": "optimize-to-webtorrent",   "videoUUID": "ba3727a3-18cf-4055-8f49-b887881e3ed3",   "isNewVideo": true }
Error: ENOENT: no such file or directory, copyfile peertube/tmp/35181-transcoded.mp4' -> 'peertube/storage/videos/ba3727a3-18cf-4055-8f49-b887881e3ed3-1080.mp4'

````

This then results in a failed upload with the complaint "Something went wrong, Video not found"

PeerTube is running at 3.2.1.

**Comment by Chocobozzz** [comment]
Could you paste the `storage` of your peertube config?

**Comment by verymilan** [comment]
Looks like this:
````
storage:
  tmp: '<r>/peertube/tmp/'
  avatars: '<r>/peertube/storage/avatars/'
  videos: '<r>/peertube/storage/videos/'
  redundancy: '<r>/peertube/storage/redundancy/'
  streaming_playlists: '<r>/peertube/storage/streaming-playlists/'
  logs: '<r>/log/peertube/'
  previews: '<r>/peertube/storage/previews/'
  thumbnails: '<r>/peertube/storage/thumbnails/'
  torrents: '<r>/peertube/storage/torrents/'
  captions: '<r>/peertube/storage/captions/'
  cache: '<r>/peertube/storage/cache/'
  plugins: '<r>/peertube/storage/plugins/'
````
But yea, most of the times it works which is odd...

**Comment by Chocobozzz** [comment]
What is `<r>`?

**Comment by verymilan** [comment]
Hm looks lime my reply mail doesn't arrive - its just a redacted path, thats all. /storage/ is the mounted network storage, log and tmp are local

**Comment by busstop1982** [comment]
I have a similar issue: the 'optimize-to-webtorrent' job worked just fine, but the subsequent transcoding to new resolutions failed:

```
Job: 18061 
Type: video-transcoding 
Processed on Aug 17, 2021, 9:59:49 AM 
Finished on Aug 17, 2021, 10:01:41 AM
{  
 "type": "new-resolution-to-webtorrent",   
 "videoUUID": "c28128ec-a46a-45c4-bc6f-39b681e75cb2",   
 "resolution": 720,  
 "isPortraitMode": false
}
Error: ENOENT: no such file or directory, stat '/var/www/peertube/storage/tmp/c28128ec-a46a-45c4-bc6f-39b681e75cb2-720.mp4'
```
(same for 360p)

i forced the transcoding job with 
```
NODE_CONFIG_DIR=/var/www/peertube/config NODE_ENV=production npm run create-transcoding-job -- -v c28128ec-a46a-45c4-bc6f-39b681e75cb2
```
with the same result - i watch'd the /var/www/peertube/storage/tmp folder during the transcoding and the respective mp4s did show up now and again.

Currently on peerTube 3.1.0
NodeJS: v12.21.0
npm: 6.14.11
ffmpeg: 4.2.4
and the storage section of my PT config:
```
storage:
  tmp: '/var/www/peertube/storage/tmp/' # Use to download data (imports etc), store uploaded files before processing...
  avatars: '/var/www/peertube/storage/avatars/'
  videos: '/var/www/peertube/storage/videos/'
  streaming_playlists: '/var/www/peertube/storage/streaming-playlists/'
  redundancy: '/var/www/peertube/storage/redundancy/'
  logs: '/var/www/peertube/storage/logs/'
  previews: '/var/www/peertube/storage/previews/'
  thumbnails: '/var/www/peertube/storage/thumbnails/'
  torrents: '/var/www/peertube/storage/torrents/'
  captions: '/var/www/peertube/storage/captions/'
  cache: '/var/www/peertube/storage/cache/'
  plugins: '/var/www/peertube/storage/plugins/'
  client_overrides: '/var/www/peertube/storage/client-overrides/'
```
