### ISSUE TITLE
Can't connnect to database Ubuntu 20.04.1LTS

### ISSUE THREAD

**Issue by LuanHimmlisch** [Chocobozzz/PeerTube#4363]
**Describe the problem**

Running fresh install of Peertube on Ubuntu throws database error although the password is correct.

**Additional information**

* PeerTube instance:
  * version: 3.3.0
  * NodeJS version: v14.17.5
  * PostgreSQL version: 12.8
  * Ubuntu version: 20.04.1 LTS

**Running `NODE_CONFIG_DIR=/var/www/peertube/config NODE_ENV=production sudo -u peertube npm start`** 
```
captain@peertube:/var/www/peertube/peertube-latest$ sudo NODE_CONFIG_DIR=/var/www/peertube/config NODE_ENV=production sudo -u peertube npm start

> peertube@3.3.0 start /var/www/peertube/versions/peertube-v3.3.0
> node dist/server

[localhost:9000] 2021-08-28 20:00:51.948 warn: Emailer is disabled so the contact form will not work.
[localhost:9000] 2021-08-28 20:00:53.570 error: Unable to connect to PostgreSQL database. {
  "err": {
    "stack": "SequelizeConnectionError: password authentication failed for user \"peertube\"\n    at Client._connectionCallback (/var/www/peertube/versions/peertube-v3.3.0/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:184:24)\n    at Client._handleErrorWhileConnecting (/var/www/peertube/versions/peertube-v3.3.0/node_modules/pg/lib/client.js:305:19)\n    at Client._handleErrorMessage (/var/www/peertube/versions/peertube-v3.3.0/node_modules/pg/lib/client.js:325:19)\n    at Connection.emit (events.js:400:28)\n    at Connection.emit (domain.js:470:12)\n    at /var/www/peertube/versions/peertube-v3.3.0/node_modules/pg/lib/connection.js:114:12\n    at Parser.parse (/var/www/peertube/versions/peertube-v3.3.0/node_modules/pg-protocol/dist/parser.js:40:17)\n    at Socket.<anonymous> (/var/www/peertube/versions/peertube-v3.3.0/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (events.js:400:28)\n    at Socket.emit (domain.js:470:12)\n    at addChunk (internal/streams/readable.js:290:12)\n    at readableAddChunk (internal/streams/readable.js:265:9)\n    at Socket.Readable.push (internal/streams/readable.js:204:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)",
    "message": "password authentication failed for user \"peertube\"",
    "name": "SequelizeConnectionError",
    "parent": {
      "stack": "error: password authentication failed for user \"peertube\"\n    at Parser.parseErrorMessage (/var/www/peertube/versions/peertube-v3.3.0/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/var/www/peertube/versions/peertube-v3.3.0/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/var/www/peertube/versions/peertube-v3.3.0/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/var/www/peertube/versions/peertube-v3.3.0/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (events.js:400:28)\n    at Socket.emit (domain.js:470:12)\n    at addChunk (internal/streams/readable.js:290:12)\n    at readableAddChunk (internal/streams/readable.js:265:9)\n    at Socket.Readable.push (internal/streams/readable.js:204:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)",
      "message": "password authentication failed for user \"peertube\"",
      "length": 104,
      "name": "error",
      "severity": "FATAL",
      "code": "28P01",
      "file": "auth.c",
      "line": "330",
      "routine": "auth_failed"
    }
  }
}
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! peertube@3.3.0 start: `node dist/server`
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the peertube@3.3.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/www/peertube/.npm/_logs/2021-08-28T20_00_53_756Z-debug.log

```

**My `/var/www/peertube/config/production.yaml`**

```
listen:
  hostname: 'localhost'
  port: 9000

# Correspond to your reverse proxy server_name/listen configuration (i.e., your public PeerTube instance URL)
webserver:
  https: false
  hostname: 'myip'
  port: 443

rates_limit:
  api:
    # 50 attempts in 10 seconds
    window: 10 seconds
    max: 50
  login:
    # 15 attempts in 5 min
    window: 5 minutes
    max: 15
  signup:
    # 2 attempts in 5 min (only succeeded attempts are taken into account)
    window: 5 minutes
    max: 2
  ask_send_email:
    # 3 attempts in 5 min
    window: 5 minutes
    max: 3
# Proxies to trust to get real client IP
# If you run PeerTube just behind a local proxy (nginx), keep 'loopback'
# If you run PeerTube behind a remote proxy, add the proxy IP address (or subnet)
trust_proxy:
  - 'loopback'

# Your database name will be database.name OR "peertube"+database.suffix
database:
  hostname: '127.0.0.1'
  port: 5432
  ssl: false
  suffix: '_prod'
  username: 'peertube'
  password: 'password'
  pool:
    max: 5
```
**Running `psql -U peertube -h localhost -W peertube_prod` with the same password**

```
captain@peertube:/var/www/peertube/peertube-latest$ psql -U peertube -h localhost -W peertube_prod
Password:
psql (12.8 (Ubuntu 12.8-0ubuntu0.20.04.1))
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits: 256, compression: off)
Type "help" for help.

peertube_prod=> \l
                                List of databases
     Name      |  Owner   | Encoding | Collate |  Ctype  |   Access privileges
---------------+----------+----------+---------+---------+-----------------------
 peertube_prod | peertube | UTF8     | C.UTF-8 | C.UTF-8 |
 postgres      | postgres | UTF8     | C.UTF-8 | C.UTF-8 |
 template0     | postgres | UTF8     | C.UTF-8 | C.UTF-8 | =c/postgres          +
               |          |          |         |         | postgres=CTc/postgres
 template1     | postgres | UTF8     | C.UTF-8 | C.UTF-8 | =c/postgres          +
               |          |          |         |         | postgres=CTc/postgres
(4 rows)

```

**My `/etc/postgresql/12/main/pg_hba.conf`**

```
# Database administrative login by Unix domain socket
local   all             postgres                                peer

# TYPE  DATABASE        USER            ADDRESS                 METHOD

# "local" is for Unix domain socket connections only
local   all             all                                     peer
# IPv4 local connections:
host    all             all             127.0.0.1/32            md5
# IPv6 local connections:
host    all             all             ::1/128                 md5
# Allow replication connections from localhost, by a user with the
# replication privilege.
local   replication     all                                     peer
host    replication     all             127.0.0.1/32            md5
host    replication     all             ::1/128                 md5
```
