### ISSUE TITLE
How to set up a proxy for youtube-dl update

### ISSUE THREAD

**Issue by r6fans** [Chocobozzz/PeerTube#4465]
The error `Cannot update youtube-dl.` happens every day in my peertube instance. The logs are as follow:
```json
{
    "err": {
        "stack": "RequestError: connect ETIMEDOUT 95.143.172.170:443\n    at ClientRequest.<anonymous> (/app/node_modules/got/dist/source/core/index.js:956:111)\n    at Object.onceWrapper (events.js:421:26)\n at ClientRequest.emit (events.js:326:22)\n    at ClientRequest.EventEmitter.emit (domain.js:483:12)\n    at ClientRequest.origin.emit (/app/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)\n    at TLSSocket.socketErrorListener (_http_client.js:427:9)\n    at TLSSocket.emit (events.js:314:20)\n    at TLSSocket.EventEmitter.emit (domain.js:483:12)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n   at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16)",
        "message": "connect ETIMEDOUT 95.143.172.170:443",
        "name": "RequestError",
        "code": "ETIMEDOUT",
        "request": {
            "_readableState": {
                "objectMode": false,
                "highWaterMark": 0,
                "buffer": {
                    "head": null,
                    "tail": null,
                    "length": 0
                },
                "length": 0,
                "pipes": null,
                "pipesCount": 0,
                "flowing": null,
                "ended": false,
                "endEmitted": false,
                "reading": false,
                "sync": true,
                "needReadable": false,
                "emittedReadable": false,
                "readableListening": false,
                "resumeScheduled": false,
                "emitClose": true,
                "autoDestroy": false,
                "destroyed": true,
                "defaultEncoding": "utf8",
                "awaitDrainWriters": null,
                "multiAwaitDrain": false,
                "readingMore": false,
                "decoder": null,
                "encoding": null
            },
            "readable": true,
            "_events": {
                "pipe": [
                    null,
                    null
                ],
                "response": [
                    null,
                    null
                ]
            },
            "_eventsCount": 8,
            "_writableState": {
                "objectMode": false,
                "highWaterMark": 0,
                "finalCalled": true,
                "needDrain": false,
                "ending": true,
                "ended": true,
                "finished": false,
                "destroyed": true,
                "decodeStrings": true,
                "defaultEncoding": "utf8",
                "length": 0,
                "writing": false,
                "corked": 0,
                "sync": true,
                "bufferProcessing": false,
                "writecb": null,
                "writelen": 0,
                "afterWriteTickInfo": null,
                "bufferedRequest": null,
                "lastBufferedRequest": null,
                "pendingcb": 1,
                "prefinished": false,
                "errorEmitted": true,
                "emitClose": true,
                "autoDestroy": false,
                "bufferedRequestCount": 0,
                "corkedRequestsFree": {
                    "next": null,
                    "entry": null
                }
            },
            "writable": false,
            "allowHalfOpen": true,
            "requestInitialized": true,
            "redirects": [],
            "retryCount": 2,
            "_progressCallbacks": [],
            "options": {
                "method": "GET",
                "retry": {
                    "limit": 2,
                    "methods": [
                        "GET",
                        "PUT",
                        "HEAD",
                        "DELETE",
                        "OPTIONS",
                        "TRACE"
                    ],
                    "statusCodes": [
                        408,
                        413,
                        429,
                        500,
                        502,
                        503,
                        504,
                        521,
                        522,
                        524
                    ],
                    "errorCodes": [
                        "ETIMEDOUT",
                        "ECONNRESET",
                        "EADDRINUSE",
                        "ECONNREFUSED",
                        "EPIPE",
                        "ENOTFOUND",
                        "ENETUNREACH",
                        "EAI_AGAIN"
                    ],
                    "maxRetryAfter": null
                },
                "headers": {
                    "user-agent": "got (https://github.com/sindresorhus/got)",
                    "accept-encoding": "gzip, deflate, br"
                },
                "hooks": {
                    "init": [],
                    "beforeRequest": [],
                    "beforeRedirect": [],
                    "beforeRetry": [],
                    "beforeError": [],
                    "afterResponse": []
                },
                "decompress": true,
                "throwHttpErrors": true,
                "followRedirect": false,
                "isStream": false,
                "responseType": "text",
                "resolveBodyOnly": false,
                "maxRedirects": 10,
                "prefixUrl": "",
                "methodRewriting": true,
                "ignoreInvalidCookies": false,
                "http2": false,
                "allowGetBody": false,
                "pagination": {
                    "countLimit": null,
                    "backoff": 0,
                    "requestLimit": 10000,
                    "stackAllItems": true
                },
                "cacheOptions": {},
                "url": "https://yt-dl.org/downloads/latest/youtube-dl",
                "username": "",
                "password": "",
                "timeout": {}
            },
            "requestUrl": "https://yt-dl.org/downloads/latest/youtube-dl",
            "_cannotHaveBody": true,
            "_noPipe": true
        },
        "timings": {
            "start": 1634170018425,
            "socket": 1634170018426,
            "lookup": 1634170018426,
            "error": 1634170149526,
            "phases": {
                "wait": 1,
                "dns": 0,
                "total": 131101
            }
        }
    },
    "level": "error",
    "message": "Cannot update youtube-dl.",
    "label": "",
    "timestamp": "2021-10-14T00:09:09.527Z"
}
```

I've set up proxy in the environment variables and configuration file but this error still occurs every day.

production.yaml
```yaml
listen:
  hostname: '0.0.0.0'
  port: 9000

# Correspond to your reverse proxy "listen" configuration
webserver:
  https: true
  hostname: '127.0.0.1'
  port: 443

rates_limit:
  api:
    # 50 attempts in 1 seconds
    window: 10 seconds
    max: 0
  login:
    # 15 attempts in 5 min
    window: 5 minutes
    max: 0
  ask_send_email:
    # 3 attempts in 5 min
    window: 5 minutes
    max: 3

# Proxies to trust to get real client IP
# If you run PeerTube just behind a local proxy (nginx), keep 'loopback'
# If you run PeerTube behind a remote proxy, add the proxy IP address (or subnet)
trust_proxy:
  - 'loopback'
  - 'linklocal'
  - 'uniquelocal'


# Your database name will be database.name or "peertube"+database.suffix
database:
  hostname: 'postgres'
  port: 5432
  ssl: false
  suffix: ''
  username: 'postgres'
  password: 'postgres'

# Redis server for short time storage
redis:
  hostname: 'redis'
  port: 6379
  auth: null

# From the project root directory
storage:
  tmp: '../data/tmp/'
  avatars: '../data/avatars/'
  videos: '../data/videos/'
  streaming_playlists: '../data/streaming-playlists'
  redundancy: '../data/redundancy/'
  logs: '../data/logs/'
  previews: '../data/previews/'
  thumbnails: '../data/thumbnails/'
  torrents: '../data/torrents/'
  captions: '../data/captions/'
  cache: '../data/cache/'
  plugins: '../data/plugins/'
  # Overridable client files : logo.svg, favicon.png and icons/*.png (PWA) in client/dist/assets/images
  # Could contain for example assets/images/favicon.png
  # If the file exists, peertube will serve it
  # If not, peertube will fallback to the default fil
  client_overrides: '../data/client-overrides/'

log:
  level: 'debug' # debug/info/warning/error
  rotation:
    enabled: false

tracker:
  enabled: true
  reject_too_many_announces: false # false because we have issues with docker ws ip/port forwarding

admin:
  email: null

plugins:
  # The website PeerTube will ask for available PeerTube plugins and themes
  # This is an unmoderated plugin index, so only install plugins/themes you trust
  index:
    enabled: true
    check_latest_versions_interval: '12 hours' # How often you want to check new plugins/themes versions
    url: 'https://packages.joinpeertube.org'

import:
  videos:
    concurrency: 1
    http:
      enabled: true
      force_ipv4: false
      proxy:
        enable: true
        url: "http://proxy.squid.local:3128/"
    torrent:
      enable: false
```

Is there any other way to solve this problem?

PeerTube instance:
URL:
version: 3.4.0
NodeJS version: 12.22.6
Ffmpeg version: 4.1.6-1~deb10u1
Postgres: 13.3
Browser name/version: Google chrome 92
