### ISSUE TITLE
new docker install, Cannot generate HTML page. ENOENT: no such file or directory

### ISSUE THREAD

**Issue by rhaamo** [Chocobozzz/PeerTube#4522]
**Describe the problem**
New docker install but with config from existing instance (migration to docker), using the nginx on the host, the directory `/app/client/dist/` stays empty.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
No `.env` as I already have a working config file, changed paths in it with paths from https://github.com/Chocobozzz/PeerTube/blob/develop/support/docker/production/config/production.yaml

If I remove the volume bind from the docker-compose the content is here, but with one, nothing is generated.
I don't see anything that could generate it after build, how is that supposed to be done ?

```yml
version: '2'
services:
  peertube:
    image: "chocobozzz/peertube:production-buster"
    environment:
      - TZ=Europe/Paris
    volumes:
      # - /datas/peertube/assets:/app/client/dist
      - /datas/peertube/data:/data
      - /datas/peertube/config:/config
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      default:
        ipv4_address: 10.0.0.145
  redis:
    image: "redis:6-alpine"
    volumes:
      - /datas/peertube/redis:/data
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 10.0.0.125
networks:
  default:
    external:
      name: 'brvm0 tinc'
```

**Comment by Chocobozzz** [comment]
`/app/client/dist` is already in the `peertube:production-buster` image.

[assets](https://github.com/Chocobozzz/PeerTube/blob/develop/support/docker/production/docker-compose.yml#L61) is a named volume [our template](https://github.com/Chocobozzz/PeerTube/blob/develop/support/docker/production/docker-compose.yml) while you use an absolute path in your docker-compose.

**Comment by rhaamo** [comment]
Yes but that named volume is only going to work with a nginx in docker (for which your default config wants SSL), and I already have a global nginx for that, and adding one sandwiched just for one path Isn't really interesting nor useful.

**Comment by Chocobozzz** [comment]
I'm sorry but I'm not a docker expert, so I'm not sure how to mount a named volume in host.

Maybe you could try https://stackoverflow.com/a/49920624

**Comment by rhaamo** [comment]
Ok so with this trick apparently it is working:
```yaml
services:
  peertube:
    ...
    volumes:
      - assets:/app/client/dist
    ...
volumes:
  assets:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/datas/peertube/assets'
```

```
host # ls /datas/peertube/assets/
ar      ca-ES  de-DE  en-US  es-ES  fi-FI  gd     hu-HU  ja-JP  locale                nl-NL  pl-PL  pt-PT  sq          sv-SE  vi-VN       zh-Hant-TW
assets  cs-CZ  el-GR  eo     eu-ES  fr-FR  gl-ES  it-IT  kab    manifest.webmanifest  oc     pt-BR  ru-RU  standalone  th-TH  zh-Hans-CN
```

And the on-host nginx can access the assets.

@Chocobozzz is it possible to add that bit to the documentation of others peoples want to use a local nginx instead of a double proxy ?
