### ISSUE TITLE
Video import error in nightly builds

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#4527]
**Describe the current behavior**
The nightly build of version 3.4.1-nightly-2021-11-07 is installed on the test server. When you try to add any video from youtube, you have to wait a very long time, after which an import error appears.

**Steps to reproduce:**

1. Start importing video from youtube
2. Very long waiting time, about 1 hour
3. Import error.

Here is the log of this error

> {"level":"error","message":"Cannot execute job 4 in queue video-import.","label":"video.ustim.ru:443","payload":{"type":"youtube-dl","videoImportId":4,"fileExt":".mp4"},"err":{"stack":"Error: Cannot guess path of /var/www/peertube/storage-fs/tmp/63d041ffec5f41e8e55cfaccbd51af12ccbecd7423493c3dbbfb9f5c557c26a2-import. Directory content: 63d041ffec5f41e8e55cfaccbd51af12ccbecd7423493c3dbbfb9f5c557c26a2-import.f136.part, plugins-global.css, resumable-uploads\n    at YoutubeDLWrapper.<anonymous> (/var/www/peertube/versions/peertube-nightly-2021-11-07/dist/server/helpers/youtube-dl/youtube-dl-wrapper.js:104:19)\n    at Generator.next (<anonymous>)\n    at fulfilled (/var/www/peertube/versions/peertube-nightly-2021-11-07/node_modules/tslib/tslib.js:114:62)","message":"Cannot guess path of /var/www/peertube/storage-fs/tmp/63d041ffec5f41e8e55cfaccbd51af12ccbecd7423493c3dbbfb9f5c557c26a2-import. Directory content: 63d041ffec5f41e8e55cfaccbd51af12ccbecd7423493c3dbbfb9f5c557c26a2-import.f136.part, plugins-global.css, resumable-uploads"},"timestamp":"2021-11-08T09:01:16.385Z"}
> {"level":"info","message":"Notifying user root its video import https://youtu.be/AWUsaUcd0I8 is finished.","label":"video.ustim.ru:443","timestamp":"2021-11-08T09:01:16.388Z"}

These are the directory settings in my config file

```
# From the project root directory
storage:
  tmp: '/var/www/peertube/storage-fs/tmp/' # Use to download data (imports etc), store uploaded files before and during processing...
  bin: '/var/www/peertube/storage/bin/'
  avatars: '/var/www/peertube/storage-fs/avatars/'
  videos: '/var/www/peertube/storage-fs/videos/'
  streaming_playlists: '/var/www/peertube/storage-fs/streaming-playlists/'
  redundancy: '/var/www/peertube/storage-fs/redundancy/'
  logs: '/var/www/peertube/storage-fs/logs/'
  previews: '/var/www/peertube/storage-fs/previews/'
  thumbnails: '/var/www/peertube/storage-fs/thumbnails/'
  torrents: '/var/www/peertube/storage-fs/torrents/'
  captions: '/var/www/peertube/storage-fs/captions/'
  cache: '/var/www/peertube/storage-fs/cache/'
  plugins: '/var/www/peertube/storage/plugins/'
  # Overridable client files in client/dist/assets/images:
  # - logo.svg
  # - favicon.png
  # - default-playlist.jpg
  # - default-avatar-account.png
  # - default-avatar-video-channel.png
  # - and icons/*.png (PWA)
  # Could contain for example assets/images/favicon.png
  # If the file exists, peertube will serve it
  # If not, peertube will fallback to the default file
  client_overrides: '/var/www/peertube/storage-fs/client-overrides/'
```
Directory location
`bin: '/var/www/peertube/storage/bin/'`
I deliberately left it by default
I also tried to change the file in this youtube-dl in this directory. Nothing helped.

* PeerTube instance:
  * URL: https://video.ustim.ru
  * version: 3.4.1-nightly-2021-11-07
  * NodeJS version: v14.18.1
  * Ffmpeg version: 4.3.2-0+deb11u2
