### ISSUE TITLE
How to use yt-dlp ?

### ISSUE THREAD

**Issue by raphgilles** [Chocobozzz/PeerTube#4589]
Hello,

I just updated my instance to the v4.0.0-rc.1 and I try to replace youtube-dl by yt-dlp.

I installed yt-dlp on my server, and in the configuration I tried : 
```
import:
  # Add ability for your users to import remote videos (from YouTube, torrent...)
  videos:
    # Amount of import jobs to execute in parallel
    concurrency: 1

    http: # Classic HTTP or all sites supported by youtube-dl https://rg3.github.io/youtube-dl/supportedsites.html
      enabled: true

      youtube_dl_release:
        # Direct download URL to youtube-dl binary
        # Github releases API is also supported
        # Examples:
        #   * https://api.github.com/repos/ytdl-org/youtube-dl/releases
        #   * https://api.github.com/repos/yt-dlp/yt-dlp/releases
        url: 'https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp'

        # youtube-dl binary name
        # yt-dlp is also supported
        name: 'yt-dlp'
```

But it don't work.

What have I to do ?

Thanks.
