### ISSUE TITLE
Missing RTMPS documentation

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#4669]
**Parts of the documentation concerned:**
Server configuration

**Describe the desired information/correction**

I can't find any documentation on how to enable RTMPS.

In production.yaml.example, there is:

```yaml
  rtmps:
    enabled: false
    port: 1936
    # Absolute path
    key_file: ''
    # Absolute path
    cert_file: ''
```

Should we use the same certificate as nginx?
If so, there is a permission problem: on a standard debian installation, the peertube user has no right on the private key file (only root has access).

Also, this documentation line is missing the 1936 port: https://framagit.org/framasoft/peertube/documentation/-/blob/master/admin-configuration.md#L58
