### ISSUE TITLE
Docker cannot mount volume for /data/tmp

### ISSUE THREAD

**Issue by Tr4sK** [Chocobozzz/PeerTube#4721]
**Describe the current behavior**

I cannot mount an external volume in `/data/tmp` for my peertube instance in docker.  
Something try to `rm` the dir `/data/tmp` at launch.

I understand it can be usefull to clean that folder, but since NPM is not capable of removing a mounted folder, the webserver crash

**Steps to reproduce:**

1. add a docker volume in docker-compose
```
  peertube:
    image: chocobozzz/peertube:production-bullseye
    networks:
      default:
        ipv4_address: 172.18.0.42
    env_file:
      - .env
    ports:
     - "1935:1935" # If you don't want to use the live feature, you can comment this line
    volumes:
      - assets:/app/client/dist
      - ./docker-volume/data:/data
      - peertube-data-videos:/data/videos
      - peertube-data-tmp:/data/tmp
      - peertube-data-redundancy:/data/redundancy
      - ./docker-volume/config:/config
volumes:
  peertube-data-tmp:
    driver: local
    driver_opts:
      type: cifs
      device: //192.168.0.1/peertube/tmp/
      o: iocharset=utf8,sec=ntlmssp,file_mode=0644,dir_mode=0755,uid=999,gid=999
```

2. Start containers `docker-volume up -d`
3. Read logs

**Describe the expected behavior**

**Additional information**

* PeerTube instance:
  * URL: https://tube.tr4sk.me
  * version: 4.0.0
  * docker install

```
peertube-peertube-1   | 
peertube-peertube-1   | > peertube@4.0.0 start /app
peertube-peertube-1   | > node dist/server
peertube-peertube-1   | 
peertube-peertube-1   | [tube.tr4sk.me:443] 2022-01-13 21:53:21.793 info: Database peertube is ready.
peertube-peertube-1   | [tube.tr4sk.me:443] 2022-01-13 21:53:22.437 error: Cannot install application. {
peertube-peertube-1   |   "err": {
peertube-peertube-1   |     "stack": "Error: EBUSY: resource busy or locked, rmdir '/data/tmp/'",
peertube-peertube-1   |     "message": "EBUSY: resource busy or locked, rmdir '/data/tmp/'",
peertube-peertube-1   |     "errno": -16,
peertube-peertube-1   |     "code": "EBUSY",
peertube-peertube-1   |     "syscall": "rmdir",
peertube-peertube-1   |     "path": "/data/tmp/"
peertube-peertube-1   |   }
peertube-peertube-1   | }
peertube-peertube-1   | npm ERR! code ELIFECYCLE
peertube-peertube-1   | npm ERR! errno 255
peertube-peertube-1   | npm ERR! peertube@4.0.0 start: `node dist/server`
peertube-peertube-1   | npm ERR! Exit status 255
peertube-peertube-1   | npm ERR! 
peertube-peertube-1   | npm ERR! Failed at the peertube@4.0.0 start script.
peertube-peertube-1   | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
peertube-peertube-1   | 
peertube-peertube-1   | npm ERR! A complete log of this run can be found in:
peertube-peertube-1   | npm ERR!     /home/peertube/.npm/_logs/2022-01-13T21_53_22_618Z-debug.log
peertube-peertube-1   | 
peertube-peertube-1   | > peertube@4.0.0 start /app
peertube-peertube-1   | > node dist/server
peertube-peertube-1   | 
peertube-peertube-1   | [tube.tr4sk.me:443] 2022-01-13 21:53:39.133 info: Database peertube is ready.
peertube-peertube-1   | [tube.tr4sk.me:443] 2022-01-13 21:53:39.781 error: Cannot install application. {
peertube-peertube-1   |   "err": {
peertube-peertube-1   |     "stack": "Error: EBUSY: resource busy or locked, rmdir '/data/tmp/'",
peertube-peertube-1   |     "message": "EBUSY: resource busy or locked, rmdir '/data/tmp/'",
peertube-peertube-1   |     "errno": -16,
peertube-peertube-1   |     "code": "EBUSY",
peertube-peertube-1   |     "syscall": "rmdir",
peertube-peertube-1   |     "path": "/data/tmp/"
peertube-peertube-1   |   }
peertube-peertube-1   | }
peertube-peertube-1   | npm ERR! code ELIFECYCLE
```

It look like it comes from those lines 

https://github.com/Chocobozzz/PeerTube/blob/3726c3725506d0f8a26ded34f42d7bcfb5d0e639/server/initializers/installer.ts#L45-L60
