### ISSUE TITLE
Video import problem. Please update release.

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#4758]
**Describe the current behavior**

We kindly ask you to release a new version of Peertube, because in version 4.0.0, importing videos from youtube and other sources does not work well. I'll explain...

Release 4.0.0 is installed on the main server, in this case the file download is very slow. If you add a long video, then an import error appears. Time-out.

I tried to import these videos
https://youtu.be/fiJTWSuSpOw
https://youtu.be/7EPJEg6R3SM

```
import:
  # Add ability for your users to import remote videos (from YouTube, torrent...)
  videos:
    # Amount of import jobs to execute in parallel
    concurrency: 1

    http: # Classic HTTP or all sites supported by youtube-dl https://rg3.github.io/youtube-dl/su>
      enabled: false

      youtube_dl_release:
        # Direct download URL to youtube-dl binary
        # Github releases API is also supported
        # Examples:
        #   * https://api.github.com/repos/ytdl-org/youtube-dl/releases
        #   * https://api.github.com/repos/yt-dlp/yt-dlp/releases
        url: 'https://api.github.com/repos/yt-dlp/yt-dlp/releases'

        # youtube-dl binary name
        # yt-dlp is also supported
        name: 'yt-dlp'

      # IPv6 is very strongly rate-limited on most sites supported by youtube-dl
      force_ipv4: false

    torrent: # Magnet URI or torrent file (use classic TCP/UDP/WebSeed to download the file)
      enabled: false
```
On the test server, the nightly build 4.0.0-nightly-2022-02-01 is installed. Configuration file with the same settings. Everything works perfectly!

```
import:
  # Add ability for your users to import remote videos (from YouTube, torrent...)
  videos:
    # Amount of import jobs to execute in parallel
    concurrency: 1

    http: # Classic HTTP or all sites supported by youtube-dl https://rg3.github.io/youtube-dl/supportedsites.h>
      enabled: false

      youtube_dl_release:
        # Direct download URL to youtube-dl binary
        # Github releases API is also supported
        # Examples:
        #   * https://api.github.com/repos/ytdl-org/youtube-dl/releases
        #   * https://api.github.com/repos/yt-dlp/yt-dlp/releases
        url: 'https://api.github.com/repos/yt-dlp/yt-dlp/releases'

        # youtube-dl binary name
        # yt-dlp is also supported
        name: 'yt-dlp'

        # Path to the python binary to execute for youtube-dl or yt-dlp
        python_path: '/usr/bin/python3'

      # IPv6 is very strongly rate-limited on most sites supported by youtube-dl
      force_ipv4: false

    torrent: # Magnet URI or torrent file (use classic TCP/UDP/WebSeed to download the file)
      enabled: false
```

**Steps to reproduce:**

1. Start importing any video from youtube
2. Video is imported for a very long time. It can last about 1 hour, but then there will be a TimeOut error. Very slow download speed
3. After reinstalling the release of Peertube v4.0.0, an error began to appear  Cannot fetch remote information of this URL.

**Describe the expected behavior**
Video import should be fast, as it happens on Peertube in nightly builds.

* PeerTube instance:
  * URL: https://peervideo.ru
  * version: 4.0.0
  * NodeJS version: v14.19.0
  * Ffmpeg version: 4.3.3-0+deb11u1

* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

> {"level":"info","message":"Cannot fetch information from import for URL https://youtu.be/fiJTWSuSpOw.","label":"peervideo.ru:443","err":{"stack":"Error: Command failed with exit code 1: python /var/www/peertube/storage/bin/yt-dlp --dump-json -f bestvideo[vcodec^=avc1][height=1080]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2][height=1080]+bestaudio/bestvideo[vcodec^=avc1][height<=1080]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio/best[vcodec!*=av01][vcodec!*=vp9.2]/best https://youtu.be/fiJTWSuSpOw\nTraceback (most recent call last):\n  File \"/usr/lib/python2.7/runpy.py\", line 174, in _run_module_as_main\n    \"__main__\", fname, loader, pkg_name)\n  File \"/usr/lib/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/var/www/peertube/storage/bin/yt-dlp/__main__.py\", line 16, in <module>\n  File \"/var/www/peertube/storage/bin/yt-dlp/yt_dlp/__init__.py\", line 4\n    f'You are using an unsupported version of Python. Only Python versions 3.6 and above are supported by yt-dlp'
