### ISSUE TITLE
Environment variables for Docker Compose

### ISSUE THREAD

**Issue by floSoX** [Chocobozzz/PeerTube#477]
Hello!

Thank you for your great job!
I started with PeerTube and its `docker-compose.yml`.
I wonder, to simplify the customisation, whether it's a good idea to generalise the environment variables usage in the `docker-compose.yml` file and add a file `.env` in this directory.

For example:
```yaml
version: "3.3"

services:

  peertube:
[...]
    environment:
      PEERTUBE_HOSTNAME: my.domain.tld
[...]
      PEERTUBE_DB_PASSWORD: postgres_password
[...]
  postgres:
[...]
      POSTGRES_PASSWORD: postgres_password
```
Became:
```yaml
version: "3.3"

services:

  peertube:
[...]
    environment:
      PEERTUBE_HOSTNAME: ${PEERTUBE_HOSTNAME}
[...]
      PEERTUBE_DB_PASSWORD: ${DB_PASSWORD}
[...]
  postgres:
[...]
      POSTGRES_PASSWORD: ${DB_PASSWORD}
```

And we find, in `.env` file:
```ini
PEERTUBE_HOSTNAME="my.domain.tld"
DB_PASSWORD="postgres_password"
```

If you think it's a good idea, I can submit a pull request.

Regards,
