### ISSUE TITLE
Switching to night assembly, avatar display

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#4865]
I decided to switch from the release of version 4.1.1 to the nightly build of the version [peertube-nightly-2022-03-17](https://builds.joinpeertube.org/nightly/peertube-nightly-2022-03-17.tar.xz)
Everything works fine, but my user avatars and channel avatars are no longer displayed, a standard image is displayed instead.
Perhaps you need a manual transfer or conversion?

Although I see avatars of other users and channels, for example [this user](https://peervideo.ru/c/olmusical/videos)

But [my avatars](https://peervideo.ru/c/games/videos?s=1) stopped being displayed

here is the configuration of the latest changes

```
# PeerTube client/interface configuration
client:
  videos:
    miniature:
      # By default PeerTube client displays author username
      prefer_author_display_name: true
      display_author_avatar: true
    resumable_upload:
      # Max size of upload chunks, e.g. '90MB'
      # If null, it will be calculated based on network speed
      max_chunk_size: '3MB'
```
