### ISSUE TITLE
Redis socket configuration

### ISSUE THREAD

**Issue by sanpii** [Chocobozzz/PeerTube#4887]
**Describe the current behavior**

The `redis.socket` configuration is confusing, it’s also require to set hostname/port configuration to null.

**Steps to reproduce:**

If I only set the `redis.socket` configuration:
```yaml
redis:
  socket: '/var/run/redis/redis-server.sock'
```
The default configuration `127.0.0.1:6379` is used and the connection fails.

**Describe the expected behavior**

If the `redis.socket` is set, use it instead of default the hostname/port.

**Additional information**

This works fine:
```yaml
redis:
  hostname: null
  port: null
  socket: '/var/run/redis/redis-server.sock'
```

* PeerTube instance:
  * URL: https://tube.homecomputing.fr/
  * version: 4.1.1
  * NodeJS version: v16.14.2
  * Ffmpeg version: 4.3.3-0+deb11u1

* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

```yaml
[tube.homecomputing.fr:443] 2022-03-28 10:45:20.789 error: Cannot connect to redis {
  "err": {
    "stack": "Error: connect ECONNREFUSED 127.0.0.1:6379\n    at TCPConnectWrap.afterConnect [as oncomplet>
    "message": "connect ECONNREFUSED 127.0.0.1:6379",
    "errno": -111,
    "code": "ECONNREFUSED",
    "syscall": "connect",
    "address": "127.0.0.1",
    "port": 6379
  }
}
```
