### ISSUE TITLE
Unable to upload video on Docker-compose installation behind the Nginx reverse proxy on 4.1.1 version

### ISSUE THREAD

**Issue by amvasilyev** [Chocobozzz/PeerTube#4910]
**Describe the current behavior**

During the upload of any file, the UI shows the "unknown error" and able to proceed further with the addition. 

The error text differs from the text specified in issue #4800

From the log it seems to be the database-related error.

**Steps to reproduce:**

1. Open the "Publish" page.
2. Select the file to upload.
3. After getting to 100% the UI changes to the "Unknown error".

**Describe the expected behavior**

The video can be uploaded to the server and added to the specified channel.

**Additional information**

* PeerTube instance:
  * URL: https://video.crafted.su/
  * version: docker image chocobozzz/peertube, v4.1.1-bullseye, 414b2583e287
  * NodeJS version: bundled in docker image
  * Ffmpeg version: bundled in docker image

* Browser name, version and platforms on which you could reproduce the bug: Firefox 99 on Debian. On Yandex Browser 22.3.1.899 the upload never finishes.
* Link to browser console log if relevant: HAR log: https://www.toptal.com/developers/hastebin/bixajayuko.json
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`): https://www.toptal.com/developers/hastebin/cusaxaqovu.rb

```
[video.crafted.su:443] 2022-04-11 11:53:05.984 error: Error in controller. {
  "err": "Error\n    at Query.run (/app/node_modules/sequelize/dist/lib/dialects/postgres/query.js:50:25)\n    at /app/node_modules/sequelize/dist/lib/sequelize.js:313:28\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async PostgresQueryInterface.insert (/app/node_modules/sequelize/dist/lib/dialects/abstract/query-interface.js:297:21)\n    at async VideoModel.save (/app/node_modules/sequelize/dist/lib/model.js:2417:35)"
} - INSERT INTO "video" ("id","uuid","name","category","licence","language","privacy","nsfw","description","support","duration","views","likes","dislikes","remote","isLive","url","commentsEnabled","downloadEnabled","waitTranscoding","state","publishedAt","originallyPublishedAt","channelId","createdAt","updatedAt") VALUES (DEFAULT,$1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25) RETURNING "id","uuid","name","category","licence","language","privacy","nsfw","description","support","duration","views","likes","dislikes","remote","isLive","url","commentsEnabled","downloadEnabled","waitTranscoding","state","publishedAt","originallyPublishedAt","channelId","createdAt","updatedAt";
```

**Comment by amvasilyev** [comment]
@Chocobozzz thank you for pointing out in the direction for the research of the problem! The issue in postgresql log was:

```
2022-04-11 13:49:09.841 MSK [11634] peertube@peertube_2021 Error: incorrect syntax for type integer: "CC-NC-SA"
2022-04-11 13:49:09.841 MSK [11634] peertube@peertube_2021 Operator:  INSERT INTO "video" ("id","uuid","name","category","licence","language","privacy","nsfw","description","support","duration","views","likes","dislikes","remote","isLive","url","commentsEnabled","downloadEnabled","waitTranscoding","state","publishedAt","originallyPublishedAt","channelId","createdAt","updatedAt") VALUES (DEFAULT,$1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25) RETURNING "id","uuid","name","category","licence","language","privacy","nsfw","description","support","duration","views","likes","dislikes","remote","isLive","url","commentsEnabled","downloadEnabled","waitTranscoding","state","publishedAt","originallyPublishedAt","channelId","createdAt","updatedAt";
```

The problem was in the configuration file. Instead of the integer value the default value was set to the string. Erroneous configuration was:

```yaml
defaults:
    ...
    # CC-BY = 1, CC-SA = 2, CC-ND = 3, CC-NC = 4, CC-NC-SA = 5, CC-NC-ND = 6, Public Domain = 7
    # You can also choose a custom licence value added by a plugin
    # No licence by default
    licence: CC-NC-SA
```

The fix was quite easy - carefully read the comments.

```yaml
defaults:
    ...
    # CC-BY = 1, CC-SA = 2, CC-ND = 3, CC-NC = 4, CC-NC-SA = 5, CC-NC-ND = 6, Public Domain = 7
    # You can also choose a custom licence value added by a plugin
    # No licence by default
    licence: 5
```

Regarding your questions: yes the instance of Peertube returned the 400 error code in this scenario. Thank you once again for pointing out the research direction.

I can also note that my installation uses the external postgresql database provided by the OS distribution, not one packaged inside the container.
