### ISSUE TITLE
How to set Rate limit on PeerTube Docker Image

### ISSUE THREAD

**Issue by smilekison** [Chocobozzz/PeerTube#4916]
Hi everyone,
I can find the rate limit customization when i installed the PeerTube on my local environment with this documentation.
https://docs.joinpeertube.org/api-rest-reference.html#section/Rate-limits

However, I have deployed PeerTube using docker image in my production server and I would like to customize the rate limit there. 
Can anyone please help me on how can i setup my customized rate limit.

```
rates_limit:
  api:
    # Unlimited requests
    window: 10 seconds
    max: 0
  login:
    # Unlimited requests
    window: 5 minutes
    max: 0
  ask_send_email:
    # Unlimited requests
    window: 5 minutes
    max: 3
```
