### ISSUE TITLE
OBS Studio is not connected in the nightly build

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#4957]
**Describe the current behavior**
In the nightly build 4.1.1-nightly-2022-05-04 live video doesn't work. OBS does not connect. In the Peertube configuration file, I changed only the port to 1937.

```
 rtmp:
    enabled: true

    hostname: 'localhost'
    port: 1937

    # Public endpoint of your RTMP server
    # Use null to use the same value than `webserver.hostname`
    public_hostname: null

```

* PeerTube instance:
  * URL: https://video.ustim.ru/w/fGAbnyqfoXsMExfogCUSXv
  * version: 4.1.1-nightly-2022-05-04
  * NodeJS version: 16.14.2
  * Ffmpeg version: 4.3.3-0+deb11u1
