### ISSUE TITLE
views.videos.remote.max_age does not support -1

### ISSUE THREAD

**Issue by Tr4sK** [Chocobozzz/PeerTube#5050]
### Is there an existing issue for this?

- [X] I have searched existing issues

### Describe the desired information/correction

Hi,
I tried to set the setting viems.videos.remote.max_age to -1 as I understand in the comment but peertube crash with the error below:

```
views:
  videos:
    # PeerTube creates a database entry every hour for each video to track views over a period of time
    # This is used in particular by the Trending page
    # PeerTube could remove old remote video views if you want to reduce your database size (video view counter will not be altered)
    # -1 means no cleanup
    # Other values could be '6 months' or '30 days' etc (PeerTube will periodically delete old entries from database)
    remote:
      max_age: '30 days'
    # PeerTube buffers local video views before updating and federating the video
    local_buffer_update_interval: '30 minutes'
    ip_view_expiration: '1 hour'
```

```
peertube-peertube-1   | TypeError: Cannot read properties of null (reading 'length')                      
peertube-peertube-1   |     at parseDurationToMs (/app/dist/server/helpers/core-utils.js:50:19)           
peertube-peertube-1   |     at Object.<anonymous> (/app/dist/server/initializers/config.js:204:61)        
peertube-peertube-1   |     at Module._compile (node:internal/modules/cjs/loader:1105:14)                 
peertube-peertube-1   |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)   
peertube-peertube-1   |     at Module.load (node:internal/modules/cjs/loader:981:32)                      
peertube-peertube-1   |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)            
peertube-peertube-1   |     at Module.require (node:internal/modules/cjs/loader:1005:19)                  
peertube-peertube-1   |     at require (node:internal/modules/cjs/helpers:102:18)                         
peertube-peertube-1   |     at Object.<anonymous> (/app/dist/server/helpers/logger.js:10:18)              
peertube-peertube-1   |     at Module._compile (node:internal/modules/cjs/loader:1105:14)
```
