### ISSUE TITLE
Hide webserver and port of uploader

### ISSUE THREAD

**Issue by paxprot** [Chocobozzz/PeerTube#5175]
### Describe the problem

I'm trying to install peertube in a local network environment using docker compose, there is no hostname or ssl certificate, so my docker-compose.yml is as follow
```
version: "3.3"
services:
  webserver:
    image: chocobozzz/peertube-webserver:latest
    env_file:
      - .env
    ports:
     - "80:80"
    volumes:
      - type: bind
        source: ./docker-volume/nginx/peertube
        target: /etc/nginx/conf.d/peertube.template
      - assets:/var/www/peertube/peertube-latest/client/dist:ro
      - ./docker-volume/data:/var/www/peertube/storage
    depends_on:
      - peertube
    restart: "always"
  peertube:
    image: chocobozzz/peertube:production-bullseye
    networks:
      default:
        ipv4_address: 172.18.0.42
    env_file:
      - .env
    ports:
     - "1935:1935"
    volumes:
      - assets:/app/client/dist
      - ./docker-volume/data:/data
      - ./docker-volume/config:/config
    depends_on:
      - postgres
      - redis
      - postfix
    restart: "always"
  postgres:
    image: postgres:13-alpine
    env_file:
      - .env
    volumes:
      - ./docker-volume/db:/var/lib/postgresql/data
    restart: "always"
  redis:
    image: redis:6-alpine
    volumes:
      - ./docker-volume/redis:/data
    restart: "always"
  postfix:
    image: mwader/postfix-relay
    env_file:
      - .env
    volumes:
      - ./docker-volume/opendkim/keys:/etc/opendkim/keys
    restart: "always"
networks:
  default:
    ipam:
      driver: default
      config:
      - subnet: 172.18.0.0/16
volumes:
  assets:
```
I'm using the given nginx image as http proxy, so I moved all code blocks from port 443 to 80 in nginx config. 
I set hostname in .env to the server ip address (say 192.168.1.12), because as I tested localhost won't work. And I uncomment these two lines.
```
PEERTUBE_WEBSERVER_PORT=80
PEERTUBE_WEBSERVER_HTTPS=false
```
Server runs up, but I notice uploader's name is shown as user@192.168.1.12:80 instead of just user. When I comment these two lines, it is shown as user, however this time videos won't load. Is there a way to hide webserver name and have videos play noramally?
