### ISSUE TITLE
PeerTube-CLI error: Aborted: user quota is exceeded or video file is too big for this PeerTube instance.

### ISSUE THREAD

**Issue by khakhilev** [Chocobozzz/PeerTube#5362]
### Describe the desired information/correction

Hello, sorry to bother!
I get this error when I try to upload wideos somewhat more than 180mB through CLI:
Aborted: user quota is exceeded or video file is too big for this PeerTube instance.

There is no error while uploading large files through web interface.
I have 
```
user:
  # Default value of maximum video BYTES the user can upload (does not take into account transcoded files).
  # -1 == unlimited
  video_quota: -1
  video_quota_daily: -1
```
In my "default.yaml", copied that to "production.yaml" but to no avail.
Googling this error return only 1 result which is source file (peertube-upload.ts)
