### ISSUE TITLE
Problem using Minio S3 and base_url for streaming-playlists and videos

### ISSUE THREAD

**Issue by nkukard** [Chocobozzz/PeerTube#5559]
### Describe the current behavior

I'm struggling a bit getting Minio S3 storage working on 5.0.1 with the patch from https://github.com/Chocobozzz/PeerTube/commit/8180f60477e99c4fd70ce25729d1ca65155a6686 applied.

Here is my config...
```yaml
object_storage:
  enabled: true
  endpoint: 's3.xxxx'
  region: 'hel-1'
  upload_acl:
    public: null
    private: null
  proxy:
    proxify_private_files: true
  credentials:
    access_key_id: 'xxxx'
    secret_access_key: 'xxxx'
  max_upload_part: 100MB
  streaming_playlists:
    bucket_name: 'content'
    prefix: 'streaming-playlists/'
    base_url: 'https://cdn.xxxx/streaming-playlists'
  videos:
    bucket_name: 'content'
    prefix: 'videos/'
    base_url: 'https://cdn.xxxx/videos'
```

### Steps to reproduce

1. Download 5.0.1 source
2. Compile with Node 18
3. Add above configuration
4. Initiate a live stream

### Describe the expected behavior

From my understanding of base_url it should allow me to change the URL to that of my CDN which is populated from the S3 storage.

I'm pretty sure I'm missing something and would really appreciate any pointers on what I did wrong.

### Additional information

* PeerTube instance:
  * URL: https://oscdev.tv
  * Version: 5.0.1
  * NodeJS version: 18
  * Ffmpeg version: 5.1.2

* Browser name, version and platforms on which you could reproduce the bug: Latest Firefox
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

Here is a log snippet when trying to live stream...
```
oscdev_tv-peertube-1    | [oscdev.tv:443] 2023-01-26 08:38:19.071 info: 127.0.0.1 - - [26/Jan/2023:08:38:19 +0000] "GET /api/v1/ping HTTP/1.1" 200 4 "-" "Health Check"
oscdev_tv-peertube-1    | [oscdev.tv:443] 2023-01-26 08:38:26.370 info: rtmp://127.0.0.1:1935/live/80180730-91e5-4708-877d-79da21cd411d probing took 1219 ms (bitrate: 9216000, fps: 60, resolution: 1080)
oscdev_tv-peertube-1    | [oscdev.tv:443] 2023-01-26 08:38:26.371 info: Will mux/transcode live video of original resolution 1080. {
oscdev_tv-peertube-1    |   "allResolutions": [
oscdev_tv-peertube-1    |     720,
oscdev_tv-peertube-1    |     1080
oscdev_tv-peertube-1    |   ]
oscdev_tv-peertube-1    | }
oscdev_tv-peertube-1    | [oscdev.tv:443] 2023-01-26 08:38:26.382 error: Cannot handle sessions. {
oscdev_tv-peertube-1    |   "err": {
oscdev_tv-peertube-1    |     "stack": "TypeError: Cannot read properties of null (reading 'replace')\n    at replaceByBaseUrl (/opt/peertube/dist/server/lib/object-storage/urls.js:40:20)\n    at getHLSPublicFileUrl (/opt/peertube/dist/server/lib/object-storage/urls.js:22:12)\n    at VideoStreamingPlaylistModel.getMasterPlaylistObjectStorageUrl (/opt/peertube/dist/server/models/video/video-streaming-playlist.js:129:57)\n    at VideoStreamingPlaylistModel.getMasterPlaylistUrl (/opt/peertube/dist/server/models/video/video-streaming-playlist.js:119:29)\n    at VideoStreamingPlaylistModel.assignP2PMediaLoaderInfoHashes (/opt/peertube/dist/server/models/video/video-streaming-playlist.js:113:40)\n    at LiveManager.<anonymous> (/opt/peertube/dist/server/lib/live/live-manager.js:351:22)\n    at Generator.next (<anonymous>)\n    at fulfilled (/opt/peertube/node_modules/tslib/tslib.js:115:62)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
oscdev_tv-peertube-1    |     "message": "Cannot read properties of null (reading 'replace')"
oscdev_tv-peertube-1    |   }
oscdev_tv-peertube-1    | }
oscdev_tv-peertube-1    | [oscdev.tv:443] 2023-01-26 08:38:40.097 info: Live session ended. {
oscdev_tv-peertube-1    |   "sessionId": "V13IV6AL"
oscdev_tv-peertube-1    | }
```

**Comment by Chocobozzz** [comment]
Bug fixed in https://github.com/Chocobozzz/PeerTube/commit/8059e050ef4e800c95851ac97abbb2330fe17882

I'm sorry but I don't understand most of the questions of your message. Prefix is used to build object storage keys, and base_url to dynamically replace the schema + host of the object storage URLs.

**Comment by nkukard** [comment]
Thanks so very much @Chocobozzz for the very prompt fix, it is really appreciated.

The patch fixes the issue I reported, however I'm getting a new error.

It looks like there is a double  /streaming-playlists/streaming-playlists/  in the URL path when the player makes a request to the BASE_URL.

The files stored in the S3 bucket have a single /streaming-playlists/ component.

```
oscdev_tv-peertube-1    | [oscdev.tv:443] 2023-01-27 09:15:17.757 warn: Client log: HLS.js error: networkError - fatal: true - manifestLoadError {
oscdev_tv-peertube-1    |   "username": "nkukard",
oscdev_tv-peertube-1    |   "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
oscdev_tv-peertube-1    |   "url": "https://oscdev.tv/w/1gJskm2pHAaYfyH9hebbs1"
oscdev_tv-peertube-1    | }
oscdev_tv-peertube-1    | [oscdev.tv:443] 2023-01-27 09:15:17.758 info: REDACTED_IP - - [27/Jan/2023:09:15:17 +0000] "POST /api/v1/server/logs/client HTTP/1.1" 204 - "https://oscdev.tv/w/1gJskm2pHAaYfyH9hebbs1" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
oscdev_tv-peertube-1    | [oscdev.tv:443] 2023-01-27 09:15:17.761 error: Client log: Cannot get sha256 segments {
oscdev_tv-peertube-1    |   "username": "nkukard",
oscdev_tv-peertube-1    |   "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
oscdev_tv-peertube-1    |   "stackTrace": "Failed to fetch\nTypeError: Failed to fetch\n    at https://oscdev.tv/client/en-US/polyfills.0d72f51ffd71c69f.js:1:48837\n    at Pt.b.<computed> (https://oscdev.tv/client/en-US/polyfills.0d72f51ffd71c69f.js:1:42791)\n    at pn (https://oscdev.tv/client/en-US/143.b9abd4bb7a4137d9.js:1:152166)\n    at Co (https://oscdev.tv/client/en-US/143.b9abd4bb7a4137d9.js:1:151077)\n    at ai.getP2PMediaLoaderOptions (https://oscdev.tv/client/en-US/143.b9abd4bb7a4137d9.js:1:154264)\n    at https://oscdev.tv/client/en-US/143.b9abd4bb7a4137d9.js:1:152983\n    at Generator.next (<anonymous>)\n    at e (https://oscdev.tv/client/en-US/main.0c9cacd487d9c471.js:3:678797)\n    at m (https://oscdev.tv/client/en-US/main.0c9cacd487d9c471.js:3:678999)\n    at https://oscdev.tv/client/en-US/main.0c9cacd487d9c471.js:3:679058",
oscdev_tv-peertube-1    |   "url": "https://oscdev.tv/w/1gJskm2pHAaYfyH9hebbs1"
oscdev_tv-peertube-1    | }
```

The request to the CDN looks like this.... (base_url) 
```
oscdev_tv-nginx-cdn-1   | [27/Jan/2023:09:15:17 +0000] localhost cdn.oscdev.tv REDACTED_IP - "GET /streaming-playlists/streaming-playlists/hls/023251dc-ac1f-4e32-97fe-470b6179072c/master.m3u8 HTTP/1.1" 403 721 251 "https://oscdev.tv/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" rt=0.100 uct="0.031" uht="0.080" urt="0.080" MISS
oscdev_tv-nginx-cdn-1   | [27/Jan/2023:09:15:17 +0000] localhost cdn.oscdev.tv 2c0f:f3c8:0:c018::65 - "GET /streaming-playlists/streaming-playlists/hls/023251dc-ac1f-4e32-97fe-470b6179072c/segments-sha256.json HTTP/1.1" 403 730 258 "https://oscdev.tv/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" rt=0.104 uct="0.032" uht="0.083" urt="0.083" MISS
```

**Comment by Chocobozzz** [comment]
What is the value of BASE_URL?

**Comment by nkukard** [comment]
@Chocobozzz Ah, ok I see! the prefix should be excluded from the BASE_URL. I'll test that, thanks!

```yaml
object_storage:
  enabled: true
  endpoint: 's3.xxxx'
  region: 'hel-1'
  upload_acl:
    public: null
    private: null
  proxy:
    proxify_private_files: true
  credentials:
    access_key_id: 'xxxx'
    secret_access_key: 'xxxx'
  max_upload_part: 100MB
  streaming_playlists:
    bucket_name: 'content'
    prefix: 'streaming-playlists/'
    base_url: 'https://cdn.xxxx/streaming-playlists'
  videos:
    bucket_name: 'content'
    prefix: 'videos/'
    base_url: 'https://cdn.xxxx/videos'
```

**Comment by Chocobozzz** [comment]
Yes exactly, PeerTube will only replace the scheme and host with base url. So it's BASE_URL + S3 key. Since you've set a prefix, your S3 key is something like of `streaming-playlists/:rootKey`. Then with ` base_url: 'https://cdn.xxxx/'` PeerTube will send to the client `https://cdn.xxxx/streaming-playlists/:rootKey`

**Comment by nkukard** [comment]
Thanks so much @Chocobozzz , I'll try that out

**Comment by nkukard** [comment]
Hi there @Chocobozzz, I'm so sorry to bother you again. I've been testing this a little more and discovered two more errors.

When a user plays a live stream, it works by default on Auto. But when they change to any other resolution I get the below errors in the logs.

It looks like the URL is malformed adding a "+V1+5" to the end of it. This seems to change, I've had different values like "+V0+14".

```
oscdev_tv-peertube-1    | [oscdev.tv:443] 2023-01-28 01:45:37.163 error: Client log: Segment https://cdn.oscdev.tv/streaming-playlists/hls/b67bbd79-3355-4148-a1ac-ced439456b83/master.m3u8+V1+5 error. {
oscdev_tv-peertube-1    |   "username": "nkukard",
oscdev_tv-peertube-1    |   "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
oscdev_tv-peertube-1    |   "stackTrace": "Unknown segment name 1-000005.ts in segment validator\nError: Unknown segment name 1-000005.ts in segment validator\n    at https://oscdev.tv/client/en-US/143.b9abd4bb7a4137d9.js:1:151339\n    at Generator.next (<anonymous>)\n    at e (https://oscdev.tv/client/en-US/main.0c9cacd487d9c471.js:3:678797)\n    at m (https://oscdev.tv/client/en-US/main.0c9cacd487d9c471.js:3:678999)\n    at i.invoke (https://oscdev.tv/client/en-US/polyfills.0d72f51ffd71c69f.js:1:35839)\n    at ft.run (https://oscdev.tv/client/en-US/polyfills.0d72f51ffd71c69f.js:1:31127)\n    at https://oscdev.tv/client/en-US/polyfills.0d72f51ffd71c69f.js:1:46134\n    at i.invokeTask (https://oscdev.tv/client/en-US/polyfills.0d72f51ffd71c69f.js:1:36459)\n    at ft.runTask (https://oscdev.tv/client/en-US/polyfills.0d72f51ffd71c69f.js:1:31767)\n    at V (https://oscdev.tv/client/en-US/polyfills.0d72f51ffd71c69f.js:1:38502)",
oscdev_tv-peertube-1    |   "url": "https://oscdev.tv/w/owXMjD47EwgCj91geEKH4r"
oscdev_tv-peertube-1    | }
```

Here is my updated config...
```
object_storage:
  enabled: true
  endpoint: 's3.xxxx'
  region: 'hel-1'
  upload_acl:
    public: null
    private: null
  proxy:
    proxify_private_files: true
  credentials:
    access_key_id: 'xxxx'
    secret_access_key: 'xxxx'
  max_upload_part: 100MB
  streaming_playlists:
    bucket_name: 'content'
    prefix: 'streaming-playlists/'
    base_url: 'https://cdn.xxxx'
  videos:
    bucket_name: 'content'
    prefix: 'videos/'
    base_url: 'https://cdn.xxxx'
```
