### ISSUE TITLE
Video files in object storage nulled out when updating video privacy from private to public on Cloudflare r2

### ISSUE THREAD

**Issue by aeharding** [Chocobozzz/PeerTube#5646]
### Describe the current behavior

On Cloudflare r2, changing a video privacy from private to public will wipe out the files in object storage, making them zero length:

<img width="1311" alt="image" src="https://user-images.githubusercontent.com/2166114/221092412-f18573e5-641d-4553-aaaf-87650b6d0a9c.png">

### Steps to reproduce

1. Configure Cloudflare r2 and connect to instance
2. Upload a video, do not publish
3. Wait for it to finish transcoding and successfully moving to object storage
4. Observe you can properly play the video, and the files are properly in object storage with correct size
5. Change the video privacy to "public" (or publish)
6. Observe that the video files are wiped out 😬

### Describe the expected behavior

Video files should not be wiped out

### Additional information

* PeerTube instance:
  * URL: https://urbanists.video
  * Version: 5.0.1
  * NodeJS version: v16.19.0
  * Ffmpeg version: v4.3.5

* Browser name, version and platforms on which you could reproduce the bug: Firefox macOS
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`): I sifted through the logs and did not find anything unusual.

Any help would be greatly appreciated! If a patch is possible, I would also really, really appreciate it, this is affecting my instance https://urbanists.video.

I've attempted applying the workaround here, but it doesn't seem to fix this issue: https://github.com/Chocobozzz/PeerTube/issues/5479#issuecomment-1375433292

Object storage config:

```yaml
object_storage:
  enabled: true

  # Without protocol, will default to HTTPS
  endpoint: 'XXX.r2.cloudflarestorage.com' # 's3.amazonaws.com' or 's3.fr-par.scw.cloud' for example
    # Needs to be set to the bucket region when using AWS S3
    # region: 'us-east-5'

  upload_acl:
    # Set this ACL on each uploaded object of public/unlisted videos
    public: ''
    # Set this ACL on each uploaded object of private/internal videos
    # PeerTube can proxify requests to private objects so your users can access them
    private: ''

  proxy:
    # If private files (private/internal video files) have a private ACL, users can't access directly the ressource
    # PeerTube can proxify requests between your object storage service and your users
    # If you disable PeerTube proxy, ensure you use your own proxy that is able to access the private files
    # Or you can also set a public ACL for private files in object storage if you don't want to use a proxy
    proxify_private_files: true

  credentials:
    # You can also use AWS_ACCESS_KEY_ID env variable
    access_key_id: 'XXX'
    # You can also use AWS_SECRET_ACCESS_KEY env variable
    secret_access_key: 'XXX'

  # Maximum amount to upload in one request to object storage
  max_upload_part: 100MB

  streaming_playlists:
    bucket_name: 'urbanists-video-prod'

    # Allows setting all buckets to the same value but with a different prefix
    prefix: 'streaming-playlists/' # Example: 'streaming-playlists:'

    # Base url for object URL generation, scheme and host will be replaced by this URL
    # Useful when you want to use a CDN/external proxy
    base_url: 'https://cdn-temp.urbanist.video' # Example: 'https://mirror.example.com'

  # Same settings but for webtorrent videos
  videos:
    bucket_name: 'urbanists-video-prod'
    prefix: 'videos/'
    base_url: 'https://cdn-temp.urbanist.video'

```
