### ISSUE TITLE
Saving configuration results in  `Error Incorrect request parameters: signup.requiresApproval`

### ISSUE THREAD

**Issue by lightweight** [Chocobozzz/PeerTube#5720]
### Describe the problem

After finally getting my Peertube instance working (I needed to set PEERTUBE_WEBSERVER_PORT=443 in my .env to fix the Invalid Client error that was prevented logins) at the same time as I upgraded it to 5.1.0. I've been able to create users and upload & play videos successfully, but every attempt to 'update configuration' (e.g. on https://vid.fossdle.org/admin/config/edit-custom#instance-homepage) as the admin user fails with 

`Error Incorrect request parameters: signup.requiresApproval`

The logs show

```
vidfossdleorg-peertube-1   | [vid.fossdle.org:443] 2023-03-30 23:17:50.682 error: Client log: Error: Incorrect request parameters: signup.requiresApproval {
vidfossdleorg-peertube-1   |   "username": "root",
vidfossdleorg-peertube-1   |   "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0",
vidfossdleorg-peertube-1   |   "url": "https://vid.fossdle.org/admin/config/edit-custom#instance-homepage"
vidfossdleorg-peertube-1   | }
```
but I cannot figure out what might be causing it! Is it a setting that's already been saved? (I *think* there might've been one successful configuration save before every subsequent 'update configuration' resulted in the above error. 
Any insight would be greatly appreciated!

### Additional information

* PeerTube instance URL: https://vid.fossdle.org
* PeerTube version: 5.1.0
* NodeJS version: v16.19.1
* Ffmpeg version: 4.3.5-0+deb11u1
* Redis version: 6.2.11
* PostgreSQL version: 13.10
(Docker install)

**Comment by Chocobozzz** [comment]
Hello,

Have you follow https://docs.joinpeertube.org/install/docker#upgrade for your upgrade? In particular `docker-compose down -v` command.

**Comment by Chocobozzz** [comment]
Can you paste your docker-compose?

**Comment by lightweight** [comment]
Here's the `docker-compose.yml`:
```
version: "3.3"

services:
  webserver:
    image: chocobozzz/peertube-webserver:latest
    env_file:
      - .env
    ports:
      - "127.0.0.1:7080:80"
    volumes:
      - /home/data/vid.fossdle.org/nginx/peertube:/etc/nginx/conf.d/peertube.template:ro
      - /home/data/vid.fossdle.org/assets:/var/www/peertube/peertube-latest/client/dist:ro
      - /home/data/vid.fossdle.org/data:/var/www/peertube/storage
    depends_on:
      - peertube
    restart: "unless-stopped"

  peertube:
    image: chocobozzz/peertube:production-bullseye
    env_file:
      - .env
    ports:
      - "127.0.0.1:1935:1935" # Comment if you don't want to use the live feature
#      - "127.0.0.1:9000:9000"
    expose:
      - "9000"
    volumes:
      - /home/data/vid.fossdle.org/assets:/app/client/dist
      - /home/data/vid.fossdle.org/data:/data
      - /home/data/vid.fossdle.org/config:/config
      - /home/data/vid.fossdle.org/storage:/var/www/peertube/storage
    depends_on:
      - postgres
      - redis
    restart: "unless-stopped"
    extra_hosts:
      - "vid.fossdle.org:157.245.188.3"

  postgres:
    image: postgres:13-alpine
    env_file:
      - .env
    volumes:
      - /home/data/vid.fossdle.org/postgres:/var/lib/postgresql/data
    restart: "unless-stopped"

  redis:
    image: redis:6-alpine
    volumes:
      - /home/data/vid.fossdle.org/redis:/data
```
