### ISSUE TITLE
Unable to setup Object Storage with backblaze properly

### ISSUE THREAD

**Issue by tio-trom** [Chocobozzz/PeerTube#5968]
### Describe the current behavior

I created a bucket and made it Public. I suppose I have to?

Then setup CORSE to "Share everything in this bucket with every origin"
![2023-09-11_17-41](https://github.com/Chocobozzz/PeerTube/assets/38043315/2bcb8a7b-3dde-469a-8de1-013bb198c9a5)

My current Peertube is as follows:

```
object_storage:
  enabled: false

  # Example Backblaze b2 endpoint
  endpoint: 's3.us-west-002.backblazeb2.com'
 
  upload_acl:
    # Set this ACL on each uploaded object of public/unlisted videos
    public: 'public-read'
    # Set this ACL on each uploaded object of private/internal videos
    # PeerTube can proxify requests to private objects so your users can access them
    private: 'private'

  proxy:
    # If private files (private/internal video files) have a private ACL, users can't access directly the ressource
    # PeerTube can proxify requests between your object storage service and your users
    # If you disable PeerTube proxy, ensure you use your own proxy that is able to access the private files
    # Or you can also set a public ACL for private files in object storage if you don't want to use a proxy
    proxify_private_files: true

  credentials:
    # You can also use AWS_ACCESS_KEY_ID env variable
    access_key_id: 'XXXXXX'
    # You can also use AWS_SECRET_ACCESS_KEY env variable
    secret_access_key: 'XXXXXX'

  # Maximum amount to upload in one request to object storage
  max_upload_part: 2GB

  web_videos:
    bucket_name: 'SECRETBUCKET'
    prefix: 'web-videos/'

  # Use the same bucket as for web videos but with a different prefix
  streaming_playlists:
    bucket_name: 'SECRETBUCKET'
    prefix: 'streaming-playlists/'
```

Restarted Peertube and all that.

Then I upload a video and I get a "Move to external storage failed" type of error in Peertube.

The logs are huge - https://paste.trom.tf/vozugatoli.yaml

But the interesting thing is that the videos uploaded into a folder called "streaming-playlists" - the only folder that was created inside the bucket.

And if I am to delete the video from Peertube it will not delete from the object storage.

Strange.

### Steps to reproduce

As stated above.

### Additional information

* PeerTube instance:
  * URL: https://videos.trom.tf
  * Version: 5.2.0

**Comment by tio-trom** [comment]
Based on this article https://jadin.me/setting-up-peertube-with-b2/ I managed to do it. Unsure where was the issue, maybe in the Peertube config.

```
object_storage:
  enabled: true
  endpoint: 's3.us-west-002.backblazeb2.com'
  upload_acl:
    public: 'public-read'
    private: 'private'
  videos:
    bucket_name: 'bucket'
    prefix: 'videos/'
  streaming_playlists:
    bucket_name: 'bucket'
    prefix: 'streaming-playlists/'
  credentials:
    access_key_id: 'XXXX'
    secret_access_key: 'XXXX'
```

However a few issues: When switching from a public/unlisted video to private I get this message `Resetting object ACL is not supported yet.` - if I try one more time it seems to work and the private video plays. But I have the feeling that it plays from the local storage and not remote!? How can I properly test that and would that be possible even? I wonder since the bucket is public on B2, but only accessible via my instance's URL for security reasons, then anyone can access these private video if they had the B2 url? I am quite confused....

Second, the live streams worked to stream but the reply is still in "Waiting transcoding" and here's the log:

```
error[9/12/2023, 1:11:11 AM] Cannot execute job 1473 in queue video-live-ending.

{
  "payload": {
    "videoId": 201380,
    "replayDirectory": "/home/yunohost.app/peertube/storage/streaming-playlists/hls/d51b37e9-c31e-41cf-b635-020852adf700/replay/2023-09-11T23:03:33.066Z",
    "liveSessionId": 1521,
    "streamingPlaylistId": 1620235,
    "publishedAt": "2023-09-11T23:03:49.168Z"
  },
  "err": {
    "stack": "TypeError: Cannot read properties of undefined (reading 'withVideoOrPlaylist')\n    at generateVideoMiniature (/var/www/peertube/dist/server/lib/thumbnail.js:82:92)\n    at /var/www/peertube/dist/server/lib/job-queue/handlers/video-live-ending.js:139:76\n    at Generator.next (<anonymous>)\n    at fulfilled (/var/www/peertube/node_modules/tslib/tslib.js:164:62)",
    "message": "Cannot read properties of undefined (reading 'withVideoOrPlaylist')"
  }
}
```

I have used both remote runners for the live, and local for the transcoding. Both similar issues.
