### ISSUE TITLE
Getting client tokens for host XX is forbidden

### ISSUE THREAD

**Issue by milkotodorov** [Chocobozzz/PeerTube#6014]
### Describe the current behavior

I'm setting up PeerTube with NGINX reverse proxy installed on a different host and I'm running into 2 issues explained bellow.

First let me share my NGINX config:

```
server {
    server_name "video.my.domain";
    proxy_redirect off;

    location / {
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_buffering off;
        client_max_body_size 0;
        proxy_connect_timeout  3600s;
        proxy_read_timeout  3600s;
        proxy_send_timeout  3600s;
        send_timeout  3600s;

        proxy_pass http://video.my.domain:9000;
    }
...
```

Where the `video.my.domain` is resolved to a local IP via the `hosts` file.

The PeerTube config is as follows:

```
listen:
  hostname: '0.0.0.0'
  port: 9000

# Correspond to your reverse proxy server_name/listen configuration (i.e., your public PeerTube instance URL)
webserver:
  https: true
  hostname: 'video.my.domain'
  port: 443
```

So, in this case I have the following error when try to logon:

```
Cannot retrieve OAuth Client credentials: Getting client tokens for host video.my.domain:9000 is forbidden. Ensure you have correctly configured PeerTube (config/ directory), in particular the "webserver" section.
```

If I change the section `webserver:` in the configuration of the PeerTube  to:

```
webserver:
  https: false
  hostname: 'video.my.domain'
  port: 9000
```

In this case the login works, but the playback and the download of the videos doesn't work as it tries to download them from `http://video.my.domain:9000/...`

I've looked into the `  /var/www/peertube/versions/peertube-v5.2.1/dist/server/controllers/api/oauth-clients.js` and wonder why the `host` in the request must be the same as the one in the `webserver`? This cannot be the case when the NGINX is on another host. 

Any idea how to do the whole setup correctly? Why the download link is generated based on the listen port?

Thank you!

### Additional information

=
