### ISSUE TITLE
Error on transcoding.webtorrent, Peertube will not start

### ISSUE THREAD

**Issue by jpatje** [Chocobozzz/PeerTube#6073]
### Describe the problem

Peertube does not start, there is an error in the configuration regarding transcoding.webtorrent:

_"stack": "Error: Please rename transcoding.webtorrent.enabled key to transcoding.web_videos.enabled in your configuration file\n    at checkRemovedConfigKeys (file:>
Nov 30 15:35:09 zeus peertube[7025]:     "message": "Please rename transcoding.webtorrent.enabled key to transcoding.web_videos.enabled in your configuration file"_

This is mentioned in the changelog for version 6.0.0. 

_"transcoding.webtorrent must be renamed to transcoding.web_videos:_", _referring to the production.yaml.example, line 522.

However, in the example file there are no entries for either '_transcoding.webtorrent_' or '_transcoding.web_videos_'

In my own production.yaml there also isn't any entry for it.

My best guess is that the entry for 'webtorrent: enabled: false' should be changed?

### Additional information

* PeerTube instance URL: video.yerunski.nl
* PeerTube version: 6.0.1
* NodeJS version: v21.2.0 (finally updated!)
* Ffmpeg version: 4.4.2
* Redis version: 7.2.2
* PostgreSQL version: 14.9

**Comment by dhk2** [comment]
That's weirdly broken, from the [production.yaml](https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example) it should all of this in the transcoding section

```
transcoding:
  enabled: true

  # Allow your users to upload .mkv, .mov, .avi, .wmv, .flv, .f4v, .3g2, .3gp, .mts, m2ts, .mxf, .nut videos
  allow_additional_extensions: true

  # If a user uploads an audio file, PeerTube will create a video by merging the preview file and the audio file
  allow_audio_files: true

  # Enable remote runners to transcode your videos
  # If enabled, your instance won't transcode the videos itself
  # At least 1 remote runner must be configured to transcode your videos
  remote_runners:
    enabled: false

  # Amount of threads used by ffmpeg for 1 local transcoding job
  threads: 1
  # Amount of local transcoding jobs to execute in parallel
  concurrency: 1

  # Choose the local transcoding profile
  # New profiles can be added by plugins
  # Available in core PeerTube: 'default'
  profile: 'default'

  resolutions: # Only created if the original video has a higher resolution, uses more storage!
    0p: false # audio-only (creates mp4 without video stream, always created when enabled)
    144p: false
    240p: false
    360p: false
    480p: false
    720p: false
    1080p: false
    1440p: false
    2160p: false

  # Transcode and keep original resolution, even if it's above your maximum enabled resolution
  always_transcode_original_resolution: true

  # Generate videos in a web compatible format
  # If you also enabled the hls format, it will multiply videos storage by 2
  # If disabled, breaks federation with PeerTube instances < 2.1
  web_videos:
    enabled: false

  # /!\ Requires ffmpeg >= 4.1
  # Generate HLS playlists and fragmented MP4 files. Better playback than with Web Videos:
  #     * Resolution change is smoother
  #     * Faster playback in particular with long videos
  #     * More stable playback (less bugs/infinite loading)
  # If you also enabled the web videos format, it will multiply videos storage by 2
  hls:
    enabled: true
```
