### ISSUE TITLE
How to set rate limits as unlimit?

### ISSUE THREAD

**Issue by r6fans** [Chocobozzz/PeerTube#6089]
### Describe the problem

This is my current rate limits configure
```yaml
rates_limit:
  api:
    window: 10 seconds
    max: 0
  login:
    window: 5 minutes
    max: 0
  signup:
    window: 5 minutes
    max: 0
  ask_send_email:
    window: 5 minutes
    max: 0
  receive_client_log:
    window: 10 minutes
    max: 0
  plugins:
    window: 10 seconds
    max: 0
  well_known:
    window: 10 seconds
    max: 0
  feeds:
    window: 10 seconds
    max: 0
  activity_pub:
    window: 10 seconds
    max: 0
  client:
    window: 10 seconds
    max: 0
```
When I visit the page, I receive `429 Too many request` error. 

If I want to set all peertube rate limits to unlimited in v6.0.1, what value should I set?

### Additional information

* PeerTube instance URL:
* PeerTube version: v6.0.1
* NodeJS version: v18.19.0
* Ffmpeg version: 
* Redis version: 7.0
* PostgreSQL version: 13.3

**Comment by Chocobozzz** [comment]
Hello,

It's not possible to disable rate limit since the v7 of rate-limit package we use: https://github.com/express-rate-limit/express-rate-limit/releases/tag/v7.0.0

We should add the support directly in PeerTube. In the meantime, you can set a big `max` value for a low `window`.

**Comment by r6fans** [comment]
> Hello,
> 
> It's not possible to disable rate limit since the v7 of rate-limit package we use: https://github.com/express-rate-limit/express-rate-limit/releases/tag/v7.0.0
> 
> We should add the support directly in PeerTube. In the meantime, you can set a big `max` value for a low `window`.

Thanks for reply!
I will try to set a big `max` value

**Comment by AarishMansur** [comment]
hey @Chocobozzz is this issue still relevant?  If Yes then is  using `max<=0` as a signal to disable rate limiting acceptable, or would you prefer a separate config flag like `enabled: false?`

**Comment by m-altaifi** [comment]
This is now possible on `develop` / the upcoming v8.3.0: every `rates_limit` section takes an `enabled` flag.

```yaml
rates_limit:
  api:
    enabled: false
```

`buildRateLimiter` short-circuits to a pass-through middleware when it is false, so the limiter is genuinely off rather than counting against a large `max`:

https://github.com/Chocobozzz/PeerTube/blob/develop/server/core/middlewares/rate-limiter.ts#L22-L24

All 15 rate limiters pass it through: `api`, `login`, `signup`, `ask_send_email`, `confirm_token`, `receive_client_log`, `plugins`, `well_known`, `feeds`, `activity_pub`, `client`, `report_abuse`, `create_comment`, `download_generate_video`.

Note it is not in v8.2.x, so the large-`max` workaround is still needed until 8.3.0 is released.

It was missing from the 8.3 release notes, so I opened #7776 to document it.
