### ISSUE TITLE
Let Admins Change 'Live' Port Off of 1935

### ISSUE THREAD

**Issue by vencabot** [Chocobozzz/PeerTube#6150]
### Describe the problem to be solved

The standard port for RTMP is 1935, and this is what Peertube uses. I have two other RTMP services on the same box (Owncast and an nginx restream server), both of which want to use port 1935, since that's the standard port.

Thankfully, Owncast's web console allows me to simply change the port in the GUI. I was able to simply change nginx's port in its config file.

That's lucky, because it seems like there's no way to change it with Peertube? When Googling this, I found other users on various messageboards having the same issue: they needed to move the ports for their other RTMP services because there seemed to be no way to make Peertube relinquish 1935.

### Describe the solution you would like

Peertube should have a text field somewhere in its admin console, like Owncast does, where the RTMP listening port can be set.

**Comment by dhk2** [comment]
Does changing the RTMP port number in production.yaml not work?
```
  # Your firewall should accept traffic from this port in TCP if you enable live
  rtmp:
    enabled: true

    # Listening hostname/port for RTMP server
    # '::' to listen on IPv6 and IPv4, '0.0.0.0' to listen on IPv4
    # Use null to automatically listen on '::' if IPv6 is available, or '0.0.0.0' otherwise
    hostname: null
    port: 1935
```
