### ISSUE TITLE
Live with object storage throws an error when starting the stream

### ISSUE THREAD

**Issue by lantrix** [Chocobozzz/PeerTube#6269]
### Describe the current behavior

New peertube installation. Starting a live then streaming RTMP from OBS to the live, the streamer gets buffering on the live, then it drops and finishes.
Backend logs start throwing a bunch of errors like

```
error[14/03/2024, 12:01:11 pm] Cannot copy segment /data/peertube/storage/streaming-playlists/hls/aace92fc-201b-44df-a561-6f3cbf27d6e1/0-000135.ts to replay directory.

{
  "err": {
    "stack": "Error: ENOENT: no such file or directory, open '/data/peertube/storage/streaming-playlists/hls/aace92fc-201b-44df-a561-6f3cbf27d6e1/0-000135.ts'",
    "message": "ENOENT: no such file or directory, open '/data/peertube/storage/streaming-playlists/hls/aace92fc-201b-44df-a561-6f3cbf27d6e1/0-000135.ts'",
    "errno": -2,
    "code": "ENOENT",
    "syscall": "open",
    "path": "/data/peertube/storage/streaming-playlists/hls/aace92fc-201b-44df-a561-6f3cbf27d6e1/0-000135.ts"
  },
  "tags": [
    "live",
    "ESCKC2DV",
    "aace92fc-201b-44df-a561-6f3cbf27d6e1"
  ]
}
```

In this case the `0-000135.ts` is no longer on the local storage, but is in B2 as a zero byte object
![Screenshot 2024-03-14 at 12 35 35](https://github.com/Chocobozzz/PeerTube/assets/117008/6faadcc9-9ab8-47c3-adf5-b354c8bc1139)

### Steps to reproduce

1. Setup a new instance using _Any OS (Recommended)_ guide 
2. Configured with below object storage which is using b2
3. Start a live
4. Stream RTMP from OBS

Live starts buffering and the errors are thrown constantly.

### Describe the expected behavior

Can start a live, stream RTMP from OBS and it works until the stream stops.

### Additional information

* PeerTube instance:
  * URL: stream.gigaohm.bio
  * Version: `6.0.3`
  * NodeJS version: `v20.11.1`
  * Ffmpeg version: `ffmpeg version 4.4.2-0ubuntu0.22.04.1`

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant: NA
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

Error example above

Config for object storage (it's a J2 template where `{{ }}` get populated during setup of the server):

```yaml
object_storage:
  enabled: true
  endpoint: "{{ peertube_object_storage_endpoint }}"
  region: "{{ peertube_object_storage_region}}"

  upload_acl:
    public: null
    private: null

  proxy:
    proxify_private_files: true

  credentials:
    access_key_id: "{{ peertube_b2_access_key_id }}"
    secret_access_key: "{{ peertube_b2_secret_access_key }}"

  max_upload_part: 100MB

  streaming_playlists:
    bucket_name: "{{ peertube_b2_bucket_name }}"
    prefix: "streaming-playlists/"
    base_url: "" # Example: 'https://mirror.example.com'

  web_videos:
    bucket_name: "{{ peertube_b2_bucket_name }}"
    prefix: "videos/"
    base_url: ""
```
