### ISSUE TITLE
Unknown InfoHash error in Tracker causes Websocket /tracker/socket to be unavailable for connection

### ISSUE THREAD

**Issue by ilfarpro** [Chocobozzz/PeerTube#6491]
### Describe the current behavior

I've been dealing with Websocket connection error lately and done quite a few testing environments, where determined that sometimes for some reason Info Hash of uploaded video becomes inavalid. It happens often enough to bother. The only solution I found - is to reupload video and process it again. But it costs a lot, since I do high quality transcoding.

To be clear: I've done testing in Incognito mode, so browser cache does not affect testing results.

If not triggering unknown Info Hash error, then /tracker/socket is available for connection. 

![image](https://github.com/user-attachments/assets/96ce7e3f-f1c3-4f13-8ff0-c9f68ad09f46)

### Steps to reproduce

1. Find video which triggers unknown Info Hash error (for example this https://k-pop.22x22.ru/w/8jepRAkMCfFvP72XLRdv4b )
2. Play It
3. Wait till Websocket error occurs.

### Additional information

* PeerTube instance: 
  * URL: https://k-pop.22x22.ru/
  * Version: 6.0.3+ built from Git at beggining of July
  * NodeJS version: v18.20.3
  * Ffmpeg version:  7.0.1 

* Browser name, version and platforms on which you could reproduce the bug: Chrome, Incognito mode, regular mode, macOS, Windows, with VPN, without VPN, 
* Link to browser console log if relevant: (see screenshot above)
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`): 

```
warn[19.07.2024, 20:32:00] Warning in tracker.
{
  "err": {
    "stack": "Error: Unknown infoHash 19028c40d2d491ab5c27b71edb803d55877ff059 requested by ip 188.225.48.64\n    at Server.filter [as _filter] (file:///app/dist/core/controllers/tracker.js:50:16)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
    "message": "Unknown infoHash 19028c40d2d491ab5c27b71edb803d55877ff059 requested by ip 188.225.xx.xx"
  }
}
```

**Comment by ilfarpro** [comment]
I use default config, only this things overrided:
```
  GNU nano 6.2                                                                                      production.yaml                                                                                               
# Update default PeerTube values
# Set by API when the field is not provided and put as default value in client
defaults:
  # Change default values when publishing a video (upload/import/go Live)
  publish:
    download_enabled: false

    comments_enabled: true

    # public = 1, unlisted = 2, private = 3, internal = 4
    privacy: 2

    # CC-BY = 1, CC-SA = 2, CC-ND = 3, CC-NC = 4, CC-NC-SA = 5, CC-NC-ND = 6, Public Domain = 7
    # You can also choose a custom licence value added by a plugin
    # No licence by default
    licence: null

thumbnails:
  # When automatically generating a thumbnail from the video
  generation_from_video:
    # How many frames to analyze at the middle of the video to select the most appropriate one
    # Increasing this value will increase CPU and memory usage when generating the thumbnail, especially for high video>    # Minimum value is 2
    frames_to_analyze: 50

  # Only two sizes are currently supported for now (not less, not more)
  # 1 size for the thumbnail (displayed in video miniatures)
  # 1 size for the preview (displayed in the video player)
  sizes:
    -
      width: 560
      height: 317

    -
      width: 1280
      height: 720
```
