### ISSUE TITLE
Custom storage config does not work

### ISSUE THREAD

**Issue by DavidLibeau** [Chocobozzz/PeerTube#651]
* **PeerTube version or URL:** beta.8

* **What is the expected behaviour?**
I want change the storage path like that, in `config/production.yaml` : 
```
# From the project root directory
storage:
  avatars: '/home/peertube/storage/avatars/'
  videos: '/home/peertube/storage/videos/'
  logs: '/home/peertube/storage/logs/'
  previews: '/home/peertube/storage/previews/'
  thumbnails: '/home/peertube/storage/thumbnails/'
  torrents: '/home/peertube/storage/torrents/'
  cache: '/home/peertube/storage/cache/'
```

* **What do you see instead?**
404 error.
I did a `sudo -u peertube ln -s /home/peertube/storage /var/www/peertube/storage` to resolve the issue but PeerTube should do it by itself, no?
