### ISSUE TITLE
videos_limit_per_synchronization having no effect

### ISSUE THREAD

**Issue by TankieTanuki** [Chocobozzz/PeerTube#6569]
### Describe the current behavior

Several videos are being imported from youtube every couple minutes by the same user.

### Steps to reproduce

1.  Set these parameters in production.yaml
```
import:
  videos:
    timeout: '1 hour'
  video_channel_synchronization:
    max_per_user: 10
    check_interval: '1 hour'
    videos_limit_per_synchronization: 1
    full_sync_videos_limit: 500

```
2. Restart peertube to have the settings take effect.
3. Have a user create a sync to a youtube channel with a large number of videos.

### Describe the expected behavior

Only one video should be imported per hour per user.

### Additional information

* PeerTube instance: TankieTube
  * URL: tankie.tube
  * Version: 6.2.1
  * NodeJS version: v18.20.4
  * Ffmpeg version: 5.1.6-0+deb12u1
