### ISSUE TITLE
Use case insensitive email for reset password

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#6570]
### Describe the current behavior

We get a lot of emails from users that says that they've requested a password reset, but they don't receive any email. When I search for their email, user id and username in the logs and audit log I can't find anything.

Relevant config:

```
log:
  level: 'info' # 'debug' | 'info' | 'warn' | 'error'

smtp:
  # smtp or sendmail
  transport: smtp
  # Path to sendmail command. Required if you use sendmail transport
  sendmail: null
  hostname: 'smtp.eu.mailgun.org'
  port: 587 # If you use StartTLS: 587
```

Whilst I know it works for other users. Possible causes:
* Handling errors by the users / bad UX
* Peertube fails to create the email job
* Mailgun issue

To investigate this further we may need to add more logging to determine what's going wrong. As far as I can see there's no audit logs for password resets, can we add that? Also we could add some info log here to tell that an email is being prepared. https://github.com/Chocobozzz/PeerTube/blob/a06c2ea020a353cdf773708832d3fa7c20f47999/server/core/lib/job-queue/job-queue.ts#L355

### Steps to reproduce

1.
2.
3.

### Additional information

* PeerTube instance:
  * URL:
  * Version: 6.2.1
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):
