### ISSUE TITLE
Transcription Generation Does Not Work

### ISSUE THREAD

**Issue by MattyBoombalatty** [Chocobozzz/PeerTube#6595]
### Describe the current behavior

Using `whisper-ctranslate2`, it appears that videos do not get transcribed. Please note that this is a GPU accelerated server and the dependencies have been referenced correctly. 

Error
```
{
  "payload": {
    "videoUUID": "750bd3d2-1f13-4a05-bd80-ef63b4917acb"
  },
  "err": {
    "stack": "Error: ENOENT: no such file or directory, open '/mnt/md0/peertube/tmp/transcription/1YvFhDvoyAZhnu99UQowEB/19a4c40d-37a3-499c-af72-32af862ac185-0-fragmented.json'",
    "message": "ENOENT: no such file or directory, open '/mnt/md0/peertube/tmp/transcription/1YvFhDvoyAZhnu99UQowEB/19a4c40d-37a3-499c-af72-32af862ac185-0-fragmented.json'",
    "errno": -2,
    "code": "ENOENT",
    "syscall": "open",
    "path": "/mnt/md0/peertube/tmp/transcription/1YvFhDvoyAZhnu99UQowEB/19a4c40d-37a3-499c-af72-32af862ac185-0-fragmented.json"
  }
}
```

production.yaml

```
video_transcription:
  # Enable automatic transcription of videos
  enabled: true

  # Choose engine for local transcription
  # Supported: 'openai-whisper' or 'whisper-ctranslate2'
  engine: 'whisper-ctranslate2'

  # You can set a custom engine path for local transcription
  # If not provided, PeerTube will try to automatically install it in the PeerTube bin directory
  engine_path: null #'/var/www/peertube/.local/bin/whisper-ctranslate2'

  # Choose engine model for local transcription
  # Available for 'openai-whisper' and 'whisper-ctranslate2': 'tiny', 'base', 'small', 'medium', 'large-v2' or 'large-v3'
  model: 'small'

  # Or specify the model path:
  #  * PyTorch model file path for 'openai-whisper'
  #  * CTranslate2 Whisper model directory path for 'whisper-ctranslate2'
  # If not provided, PeerTube will automatically download the model
  model_path: '/var/www/peertube/.local/lib/python3.10/site-packages/ctranslate2.libs' #/libcudnn-463fd6d5.so.8.9.7'

  # Enable remote runners to transcribe videos
  # If enabled, your instance won't transcribe the videos itself
  # At least 1 remote runner must be configured to transcribe your videos
  remote_runners:
    enabled: false
```

### Steps to reproduce

1.
2.
3.

### Additional information

* PeerTube instance:
  * URL: https://nicecrew.tv
  * Version: 6.3.0
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):
