### ISSUE TITLE
Long Form Videos Fail to Transcode

### ISSUE THREAD

**Issue by MattyBoombalatty** [Chocobozzz/PeerTube#6622]
### Describe the current behavior

Long-form videos with transcription enabled will fail to publish after transcoding. I have the 480p and original resolution transcoded. In the admin panel, all the resolutions are there plus the audio only file, but it stays on "waiting for transcode".

Please note that even after disabling transcription and re-running the transcoding job, the result is the same (transcoding fails). An example can be found [here](https://nicecrew.tv/w/oRXYna9PzhA839QMQZKuCS)

When the transcoding job is forced, this is the error:

```
{
  "type": "new-resolution-to-web-video",
  "videoUUID": "8554f991-4152-48cd-97ff-e3aaf38bd9fb",
  "isNewVideo": false,
  "resolution": 480,
  "fps": 30,
  "hasChildren": false
}
TypeError: Cannot read properties of undefined (reading 'toActivityPubObject')
    at file:///var/www/peertube/versions/peertube-v6.3.0/dist/core/models/video/formatter/video-activity-pub-format.js:176:21
    at Array.map (<anonymous>)
    at buildIcon (file:///var/www/peertube/versions/peertube-v6.3.0/dist/core/models/video/formatter/video-activity-pub-format.js:176:10)
    at videoModelToActivityPubObject (file:///var/www/peertube/versions/peertube-v6.3.0/dist/core/models/video/formatter/video-activity-pub-format.js:38:317)
    at VideoModel.toActivityPubObject (file:///var/www/peertube/versions/peertube-v6.3.0/dist/core/models/video/video.js:881:33)
    at sendUpdateVideo (file:///var/www/peertube/versions/peertube-v6.3.0/dist/core/lib/activitypub/send/send-update.js:19:37)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async federateVideoIfNeeded (file:///var/www/peertube/versions/peertube-v6.3.0/dist/core/lib/activitypub/videos/federate.js:18:9)
    at async moveToPublishedState (file:///var/www/peertube/versions/peertube-v6.3.0/dist/core/lib/video-state.js:107:5)
    at async /var/www/peertube/versions/peertube-v6.3.0/node_modules/sequelize/lib/sequelize.js:507:18
```

### Additional information

* PeerTube instance:
  * URL: https://nicecrew.tv
  * Version: 6.3.0
  * NodeJS version: 20.17.0
  * Ffmpeg version: 4.4.2

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Thanks! The root cause of the issue if the video doesn't have a thumbnail/preview which is very weird. Do you know how you uploaded this video?

**Comment by MattyBoombalatty** [comment]
This was a live stream from another user. I wonder... Let me see what happens if I upload a thumbnail and then redo the transcoding. I have custom video thumbnails so it's entirely possible I didn't replace the default ones correctly.

**Comment by MattyBoombalatty** [comment]
Okay, manually uploading a thumbnail and then re-transcoding fixed the issue. I wonder why it's not automatically generating thumbnails for all videos...

**Comment by MattyBoombalatty** [comment]
I reset the video thumbnail generation sizes back to normal (I had doubled them) so we'll see if that works.

```
thumbnails:

  # When automatically generating a thumbnail from the video

  generation_from_video:

    # How many frames to analyze at the middle of the video to select the most appropriate one

    # Increasing this value will increase CPU and memory usage when generating the thumbnail, especially for high video resolution

    # Minimum value is 2

    frames_to_analyze: 20
  # Only two sizes are currently supported for now (not less, not more)
  # 1 size for the thumbnail (displayed in video miniatures)
  # 1 size for the preview (displayed in the video player)
  sizes:
    -
      width: 280 # 280
      height: 157 # 157

    -
      width: 850 # 850
      height: 480 # 480
```
