### ISSUE TITLE
Add rtmp(s) entries to custom-environment-variables.yaml

### ISSUE THREAD

**Issue by Ryvix** [Chocobozzz/PeerTube#6707]
### Describe the problem to be solved

I think adding entries for rtmp and rtmps to the /support/docker/production/config/custom-environment-variables.yaml file is a good idea to be able to edit them through env vars.

### Describe the solution you would like

Example addition:

```yaml
live:
  rtmp:
    enabled: "PEERTUBE_LIVE_RTMP_ENABLED"
    port: "PEERTUBE_LIVE_RTMP_PORT"
    # Use 0.0.0.0 to listen on all
    hostname: "PEERTUBE_LIVE_RTMP_HOSTNAME"
    public_hostname: "PEERTUBE_LIVE_RTMP_PUBLIC_HOSTNAME"
  rtmps:
    enabled: "PEERTUBE_LIVE_RTMPS_ENABLED"
    port: "PEERTUBE_LIVE_RTMPS_PORT"
    # Use 0.0.0.0 to listen on all
    hostname: "PEERTUBE_LIVE_RTMPS_HOSTNAME"
    public_hostname: "PEERTUBE_LIVE_RTMPS_PUBLIC_HOSTNAME"
    key_file: "PEERTUBE_LIVE_RTMPS_KEY_FILE"
    cert_file: "PEERTUBE_LIVE_RTMPS_CERT_FILE"
```
