### ISSUE TITLE
Cloudflare R2 is not working with Peertube. 

### ISSUE THREAD

**Issue by giorgi3092** [Chocobozzz/PeerTube#6749]
### Describe the problem

Just installed latest version. Video successfully uploaded and moved to remote storage. HLS and web videos are both on (2x storage use)

My producttion.yaml:
```
static_files:
  # Require and check user authentication when accessing private files (internal/private video files)
  private_files_require_auth: true

object_storage:
  enabled: true

  # Without protocol, will default to HTTPS
  # Your S3 provider must support virtual hosting of buckets as PeerTube doesn't support path style requests
  endpoint: 'https://112f14a6d3124354510880b3412afbb7.r2.cloudflarestorage.com/fusstube' # 's3.amazonaws.com' or 's3.fr-par.scw.cloud' for example

  region: 'auto'

  upload_acl:
    # Set this ACL on each uploaded object of public/unlisted videos
    # Use null if your S3 provider does not support object ACL
    public: 'private'
    # Set this ACL on each uploaded object of private/internal videos
    # PeerTube can proxify requests to private objects so your users can access them
    # Use null if your S3 provider does not support object ACL
    private: 'private'

  proxy:
    # If private files (private/internal video files) have a private ACL, users can't access directly the ressource
    # PeerTube can proxify requests between your object storage service and your users
    # If you disable PeerTube proxy, ensure you use your own proxy that is able to access the private files
    # Or you can also set a public ACL for private files in object storage if you don't want to use a proxy
    proxify_private_files: true

  credentials:
    # You can also use AWS_ACCESS_KEY_ID env variable
    access_key_id: 'redacted'
    # You can also use AWS_SECRET_ACCESS_KEY env variable
    secret_access_key: 'redacted'

  # Maximum amount to upload in one request to object storage
  max_upload_part: 100MB

  # Maximum number of attempts to make a request to object storage
  # Some object storage providers (for instance Backblaze) expects the client to retry upload upon 5xx errors
  # If you're using such a provider then you can increase this value
  max_request_attempts: 3
  
  streaming_playlists:
    bucket_name: 'fusstube'

    # Allows setting all buckets to the same value but with a different prefix
    prefix: 'streaming-playlists:' # Example: 'streaming-playlists:'

    # Base url for object URL generation, scheme and host will be replaced by this URL
    # Useful when you want to use a CDN/external proxy
    #base_url: '' # Example: 'https://mirror.example.com'

    # PeerTube makes many small requests to the object storage provider to upload/delete/update live chunks
    # which can be a problem depending on your object storage provider
    # You can also choose to disable this feature to reduce live streams latency
    # Live stream replays are not affected by this setting, so they are uploaded in object storage as regular VOD videos
    store_live_streams: true

  web_videos:
    bucket_name: 'fusstube'
    prefix: 'web-videos:'
    #base_url: ''

  user_exports:
    bucket_name: 'fusstube'
    prefix: 'user-exports:'
    #base_url: ''

  # Same settings but for original video files
  original_video_files:
    bucket_name: 'fusstube'
    prefix: 'original-videos:'
    #base_url: ''
```

I am using default nginx config that came with installation.

Video URL: https://fusstube.com/w/e8VPiGCJnv9JZMSJGgukWL

there is CROS violation:
`Access to XMLHttpRequest at 'https://fusstube.112f14a6d3124354510880b3412afbb7.r2.cloudflarestorage.com/streaming-playlists:hls/881e3d61-841c-4290-93a6-9fafe0cac1a2/b29f9568-8027-43bb-92ec-ee703caed68d-master.m3u8' from origin 'https://fusstube.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

But in Clopudflare, I have set:
```
[
  {
    "AllowedOrigins": [
      "https://fusstube.com"
    ],
    "AllowedMethods": [
      "GET",
      "HEAD"
    ],
    "AllowedHeaders": [
      "*"
    ],
    "ExposeHeaders": [
      "ETag"
    ],
    "MaxAgeSeconds": 3000
  }
]
```

What am I getting wrong? Is this even recommended setup?

### Additional information

* PeerTube instance URL: https://fusstube.com/
* PeerTube version:  6.2
* NodeJS version:
* Ffmpeg version: 
* Redis version:
* PostgreSQL version:

EDIT:
Console reports this error:
"Access to XMLHttpRequest at 'https://fusstube.s3.eu-central-003.backblazeb2.com/streaming-playlists:hls/6a622c8c-4c9b-4cf0-a46c-6f172c1389e4/3ad3f870-e141-4df4-9758-87c0890ac880-master.m3u8' from origin 'https://fusstube.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource."
Is my setup correct?

EDIT: in Backblaze, if I set bucket to public, it works. But I should not set the bucket to public, right? Peertube should be managing access to bucket internally I believe

EDIT: I tried everything and can't get the CROS violation to go away. I feel dumb
