### ISSUE TITLE
v7 - cannot view videos with custom location

### ISSUE THREAD

**Issue by frenzybiscuit** [Chocobozzz/PeerTube#6811]
### Describe the problem

What nginx settings do I need to change for videos in custom locations to work?

The videos upload and transcode and save correctly, but clients cannot view them on the web (works fine with default locations).

```
arrow /videos/peertube # ls -l
total 59
drwxr-xr-x 2 peertube peertube 2 Jan  5 10:42 original-video-files
drwxr-xr-x 2 peertube peertube 2 Jan  5 10:44 redundancy
drwxr-xr-x 3 peertube peertube 3 Jan  5 10:45 streaming-playlists
drwxr-xr-x 4 peertube peertube 5 Jan  5 10:50 tmp
drwxr-xr-x 2 peertube peertube 2 Jan  5 10:41 tmp-persistent
drwxr-xr-x 2 peertube peertube 5 Jan  5 10:51 torrents
drwxr-xr-x 3 peertube peertube 3 Jan  5 10:45 web-videos
```

```
storage:
  tmp: '/videos/peertube/tmp/' # Use to download data (imports etc), store uploaded files before and during processing...
  tmp_persistent: '/videos/peertube/tmp-persistent/' # As tmp but the directory is not cleaned up between PeerTube restarts
  bin: '/var/www/peertube/storage/bin/'
  avatars: '/var/www/peertube/storage/avatars/'
  web_videos: '/videos/peertube/web-videos/'
  streaming_playlists: '/videos/peertube/streaming-playlists/'
  original_video_files: '/videos/peertube/original-video-files/'
  redundancy: '/videos/peertube/redundancy/'
  logs: '/var/www/peertube/storage/logs/'
  previews: '/var/www/peertube/storage/previews/'
  thumbnails: '/var/www/peertube/storage/thumbnails/'
  storyboards: '/var/www/peertube/storage/storyboards/'
  torrents: '/videos/peertube/torrents/'
  captions: '/var/www/peertube/storage/captions/'
  cache: '/var/www/peertube/storage/cache/'
  plugins: '/var/www/peertube/storage/plugins/'
  well_known: '/var/www/peertube/storage/well-known/'
```

### Additional information

* PeerTube version: 7
* NodeJS version: v22.4.1
* Ffmpeg version: 6.1.2
* Redis version: 7.4.1
* PostgreSQL version: 17.2
