### ISSUE TITLE
Clarification on PeerTube configuration persistence and theme/plugin issues

### ISSUE THREAD

**Issue by 0xSysR3ll** [Chocobozzz/PeerTube#6820]
### Describe the problem

Hello,

I usually exhaust all resources before asking for help, but in this case, I'm completely stumped. At the same time, I admire the quality of answers here, so I figured I’d give it a try.

After reviewing the documentation, I still find PeerTube's configuration architecture a bit unclear. From what I understand, configuration can be handled in three ways:

- Environment variables
 - A YAML file (`production.yaml`)
- The web interface

Here are my specific points of confusion—please correct me if I’m wrong:

- `production.yaml` behavior: This file is partially rewritten based on changes made in the web interface. However, it also allows defining some values that won't be overwritten.
- `local-production.json` behavior: This file appears to depend entirely on the web interface configuration.

The issue I’m encountering is this: after debugging for a few hours, I’ve noticed that some options set in the web interface don’t get saved to either of these files but persist after a reboot. For instance, changes to the home page configuration appear to save without errors but don’t actually apply.

Additionally, I’m unable to install themes or plugins.

To help diagnose, here are my current configurations:

## `docker-compose.yml`

```yml
name: peertube
services:
  peertube:
    image: chocobozzz/peertube:production-bookworm
    container_name: peertube
    networks:
      peertube:
      backend:
    env_file:
      - /srv/docker/data/peertube/config/.env
    volumes:
      # Remove the following line if you want to use another webserver/proxy or test PeerTube in local
      - data:/data
      - config:/config
      - assets:/app/client/dist
    depends_on:
      - postgres
      - redis
    restart: "always"

  peertube-proxy:
    image: chocobozzz/peertube-webserver:latest
    container_name: peertube-proxy
    env_file:
      - /srv/docker/data/peertube/config/.env
    labels:
    # Traefik labels
    [...]
    volumes:
      - data:/var/www/peertube/storage
      - assets:/var/www/peertube/peertube-latest/client/dist:ro
    configs:
      - source: peertube-proxy
        target: /etc/nginx/conf.d/peertube.template
    depends_on:
      - peertube
    networks:
      - peertube
      - traefik_backend
      - backend
    restart: "always"
    logging: *x-logging

# Postgres
[...]
# Redis
[...]

networks:
  peertube:
    external: true

configs:
  peertube-proxy:
    file: /srv/docker/data/peertube/nginx/peertube

volumes:
  config:
    driver: local
    driver_opts:
      type: none
      device: /srv/docker/data/peertube/config
      o: bind
  data:
    driver: local
    driver_opts:
      type: none
      device: /srv/docker/data/peertube/data
      o: bind
  db:
    driver: local
    driver_opts:
      type: none
      device: /srv/docker/data/peertube/db
      o: bind
  redis:
    driver: local
    driver_opts:
      type: none
      device: /srv/docker/data/peertube/redis
      o: bind

  assets:
  ```
  
 ##  `/srv/docker/data/peertube` directory :
  ```bash
drwxrwsr-x  2  999  999 4096 Jan  6 18:51 config
drwxrwxr-x 20  999  999 4096 Jan  6 19:32 data
drwxrwxr-x  3 1001 1001 4096 Nov 25 22:56 db
drwxrwsr-x  2  999  999 4096 Dec 29 15:59 nginx
drwxrwxr-x  3 1001 1001 4096 Jan  6 11:03 redis
drwxr-xr-x 42  999  999 4096 May  3  2024 www
```

## Plugin install logs: 
```
[peertube.esnhack.fr:443] 2025-01-06 21:20:35.715 debug: Checking POST - /api/v1/server/logs/client parameters {
  "body": {
    "message": "Backend returned code 400, errorMessage is: Cannot install plugin peertube-theme-dark",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0",
    "url": "https://peertube.esnhack.fr/admin/settings/plugins/search?pluginType=2",
    "level": "error",
    "meta": "{\"url\":\"https://peertube.esnhack.fr/api/v1/plugins/install\"}"
  },
  "params": {},
  "query": {}
}
[peertube.esnhack.fr:443] 2025-01-06 21:20:35.716 error: Client log: Backend returned code 400, errorMessage is: Cannot install plugin peertube-theme-dark {
  "username": "root",
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0",
  "meta": "{\"url\":\"https://peertube.esnhack.fr/api/v1/plugins/install\"}",
  "url": "https://peertube.esnhack.fr/admin/settings/plugins/search?pluginType=2"
}
```

Thanks in advance for any guidance!

### Additional information

* PeerTube instance URL: https://peertube.esnhack.fr
* PeerTube version: `7.0.1`
* NodeJS version: `v18.20.5`
* Ffmpeg version: `5.1.6-0+deb12u1`
* Redis version: `7.4.1`
* PostgreSQL version: `17.2`
