### ISSUE TITLE
Cannot import/upload videos from Firefox based browsers or edit them in any browser.

### ISSUE THREAD

**Issue by RiQuY** [Chocobozzz/PeerTube#6913]
### Describe the current behavior

When I try to upload a video or importing from a URL while using a Firefox based browser like Firefox or Librewolf, after clicking on "Upload video" the connection timeouts after 15~ seconds leaving a message in the browser console and in the logs. This error also happens when tried to edit the video information of an already imported video.

I tried uploading from Chrome and Brave and there the import works fine, editing don't work in any browser. I also tried removing the nginx/caddy optimizations from my webserver having the same result.

I'm using the docker deployment of Peertube 7.0.1 without plugins and the livestreams disabled, the instance is public to see (no registration allowed), you can see it in this URL. https://video.riquy.dev/

### Steps to reproduce

1. Log in to your account from a Firefox based browser.
2. Click on upload video.
3. Upload a file or an URL (for example: https://www.twitch.tv/ricardo_stryki/video/2396762617) and wait for it to fail to connect (look at JS console)
NOTE: This also happens when tried to edit the video information of an video awaiting transcoding, the editing doesn't work in any browser.

### Describe the expected behavior

The expect behaviour is being able to upload/import videos from Firefox based browsers.

### Additional information

* PeerTube instance:
  * URL: https://video.riquy.dev/
  * Version: v7.0.1 (Docker deployment with production-bookworm tag)
  * NodeJS version: v18.20.7
  * Ffmpeg version: 5.1.6-0+deb12u1

* Browser name, version and platforms on which you could reproduce the bug: LibreWolf 135.0.1-1 or Firefox 135.0
* Link to browser console log if relevant:
Error when uploading a video from Firefox based browsers.
The related POST request to "/api/v1/videos/import" appears empty.
```
Error: Could not establish connection. Receiving end does not exist. 2 [trigger-autofill-script-injection.js:5:20](moz-extension://224d1b30-8d4a-43cf-a8d0-6ecd173c9ca7/content/trigger-autofill-script-injection.js)

/******/ (function() { // webpackBootstrap
(function () {
    // FIXME: Verify that this floating promise is intentional. If it is, add an explanatory comment and ensure there is proper error handling.
    // eslint-disable-next-line @typescript-eslint/no-floating-promises
    chrome.runtime.sendMessage({ command: "triggerAutofillScriptInjection" });
})();

/******/ })()
;
```
Error log when editing a video information from any browser:
```
https://video.riquy.dev/api/v1/videos/512/source Request Method: GET Status Code: 404 Not Found
{
    "type": "about:blank",
    "title": "Not Found",
    "detail": "Video source not found",
    "status": 404,
    "docs": "https://docs.joinpeertube.org/api-rest-reference.html#operation/getVideoSource"
}

PUT https://video.riquy.dev/api/v1/videos/512 408 (Request Timeout)
No {
  error: null
  headers: t {normalizedNames: Map(0), lazyUpdate: null, lazyInit: ƒ}
  message: "Http failure response for https://video.riquy.dev/api/v1/videos/512: 408 OK"
  name: "HttpErrorResponse"
  ok: false
  status: 408
  statusText: "OK"
  url: "https://video.riquy.dev/api/v1/videos/512"
}

Backend returned code 408, errorMessage is: Error de servidor desconocido 
{
  type: undefined
  url: "https://video.riquy.dev/api/v1/videos/512"
}
```
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):
This is the relevant error logs I found in peertube.log
```
{"tags":["client"],"username":"riquy","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:135.0) Gecko/20100101 Firefox/135.0","meta":"{\"url\":\"https://video.riquy.dev/api/v1/videos/imports/\"}","url":"https://video.riquy.dev/videos/upload#import-url","level":"error","message":"Client log: Backend returned code 0, errorMessage is: Error de servidor desconocido","label":"video.riquy.dev:443","timestamp":"2025-03-06T06:07:24.997Z"}
{"tags":["http"],"level":"info","message":"83.54.0.0 - - [06/Mar/2025:06:07:24 +0000] \"POST /api/v1/server/logs/client HTTP/1.1\" 204 - \"https://video.riquy.dev/videos/upload\" \"Firefox\"","label":"video.riquy.dev:443","timestamp":"2025-03-06T06:07:24.998Z"}
{"tags":["client"],"username":"riquy","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:135.0) Gecko/20100101 Firefox/135.0","url":"https://video.riquy.dev/videos/upload#import-url","level":"error","message":"Client log: Error: Error de servidor desconocido","label":"video.riquy.dev:443","timestamp":"2025-03-06T06:07:25.002Z"}
```

The instance is behind a Caddy reverse proxy to have SSL and a domain so the webserver in the docker file is not needed.
docker-compose.yml
```
services:
  peertube:
    image: chocobozzz/peertube:production-bookworm
    container_name: peertube
    group_add:
      # HW Acceleration - getent group render | cut -d: -f3
      - "106"
    devices:  
      - /dev/dri/renderD128:/dev/dri/renderD128
    env_file:
      - peertube.env

    ports:
     - "9000:9000" # Uncomment if you use another webserver/proxy or test PeerTube in local, otherwise not suitable for production
    volumes:
      - ./data:/data
      - ./config:/config
    depends_on:
      - postgres
      - redis
      - postfix
    restart: "always"

  postgres:
    image: postgres:13-alpine
    container_name: peertube-postgres
    env_file:
      - peertube.env
    volumes:
      - ./db:/var/lib/postgresql/data
    restart: "always"

  redis:
    image: redis:6-alpine
    container_name: peertube-redis
    volumes:
      - ./redis:/data
    restart: "always"

  postfix:
    image: mwader/postfix-relay
    container_name: peertube-postfix
    env_file:
      - peertube.env
    volumes:
      - ./opendkim/keys:/etc/opendkim/keys
    restart: "always"

```

With secrets redacted.
.env
```
# Database / Postgres service configuration
POSTGRES_USER=admin
POSTGRES_PASSWORD=_______REDACTED______
# Postgres database name "peertube"
POSTGRES_DB=peertube
# Database username and password used by PeerTube must match Postgres', so they are copied:
PEERTUBE_DB_USERNAME=$POSTGRES_USER
PEERTUBE_DB_PASSWORD=$POSTGRES_PASSWORD
PEERTUBE_DB_SSL=false
# Default to Postgres service name "postgres" in docker-compose.yml
PEERTUBE_DB_HOSTNAME=postgres

# PeerTube server configuration
# If you test PeerTube in local: use "peertube.localhost" and add this domain to your host file resolving on 127.0.0.1
PEERTUBE_WEBSERVER_HOSTNAME=video.riquy.dev
# If you just want to test PeerTube on local or use a reverse proxy.
PEERTUBE_WEBSERVER_PORT=443
PEERTUBE_WEBSERVER_HTTPS=true
# If you need more than one IP as trust_proxy
# pass them as a comma separated array:
PEERTUBE_TRUST_PROXY=["127.0.0.1", "loopback", "172.18.0.0/16", "10.10.10.1", "192.168.1.171"]

# Generate one using `openssl rand -hex 32`
PEERTUBE_SECRET=_______REDACTED______

# E-mail configuration
# Default to Postfix service name "postfix" in docker-compose.yml
# May be the hostname of your Custom SMTP server
PEERTUBE_SMTP_HOSTNAME=postfix
PEERTUBE_SMTP_PORT=25
PEERTUBE_SMTP_FROM=noreply@riquy.dev
PEERTUBE_SMTP_TLS=false
PEERTUBE_SMTP_DISABLE_STARTTLS=false
PEERTUBE_ADMIN_EMAIL=peertube@riquy.dev

# Postfix service configuration
POSTFIX_myhostname=video.riquy.dev
# If you need to generate a list of sub/DOMAIN keys
# pass them as a whitespace separated string <DOMAIN>=<selector>
OPENDKIM_DOMAINS=video.riquy.dev=peertube
# see https://github.com/wader/postfix-relay/pull/18
OPENDKIM_RequireSafeKeys=no

PEERTUBE_OBJECT_STORAGE_UPLOAD_ACL_PUBLIC="public-read"
PEERTUBE_OBJECT_STORAGE_UPLOAD_ACL_PRIVATE="private"
```
