### ISSUE TITLE
S3 bucket upload: NoSuchBucket (Solved). Improvement for docs!

### ISSUE THREAD

**Issue by spirillen** [Chocobozzz/PeerTube#7004]
Solved,,, but documentation might be improved

```yaml
object_storage:
  enabled: true

  # Without protocol, will default to HTTPS
  # Your S3 provider must support virtual hosting of buckets as PeerTube doesn't support path style requests
  endpoint: 's3.de.io.cloud.ovh.net' # 's3.amazonaws.com' or 's3.fr-par.scw.cloud' for example

  region: 'de'

  upload_acl:
    # Set this ACL on each uploaded object of public/unlisted videos
    # Use null if your S3 provider does not support object ACL
    public: 'public-read'
    # Set this ACL on each uploaded object of private/internal videos
    # PeerTube can proxify requests to private objects so your users can access them
    # Use null if your S3 provider does not support object ACL
    private: 'private'

  proxy:
    # If private files (private/internal video files) have a private ACL, users can't access directly the ressource
    # PeerTube can proxify requests between your object storage service and your users
    # If you disable PeerTube proxy, ensure you use your own proxy that is able to access the private files
    # Or you can also set a public ACL for private files in object storage if you don't want to use a proxy
    proxify_private_files: true

  credentials:
    # You can also use CCESS_KEY_ID env variable
    access_key_id: ''
    # You can also use SECRET_ACCESS_KEY env variable
    secret_access_key: ''

  # Maximum amount to upload in one request to object storage
  max_upload_part: 200MB

  # Maximum number of attempts to make a request to object storage
  # Some object storage providers (for instance Backblaze) expects the client to retry upload upon 5xx errors
  # If you're using such a provider then you can increase this value
  max_request_attempts: 3

  streaming_playlists:
    bucket_name: 'Unique_bucket_name' # e.g. iodfgphgfehpgruhperuhgp this is your bucket name on the S3 server

    # Allows setting all buckets to the same value but with a different prefix
    prefix: ''
    # 'streaming-playlists'

    # Base url for object URL generation, scheme and host will be replaced by this URL
    # Useful when you want to use a CDN/external proxy
    base_url: 'https://cdn.matrix.rocks' # Example: 'https://mirror.example.com'

    # PeerTube makes many small requests to the object storage provider to upload/delete/update live chunks
    # which can be a problem depending on your object storage provider
    # You can also choose to disable this feature to reduce live streams latency
    # Live stream replays are not affected by this setting, so they are uploaded in object storage as regular VOD v>
    store_live_streams: false

  web_videos:
    bucket_name:  'Unique_bucket_name' # e.g. iodfgphgfehpgruhperuhgp, this is your bucket name on the S3 server
    prefix: 'web-videos'
    base_url: ''

  user_exports:
    bucket_name: 'Unique_bucket_name' # e.g. iodfgphgfehpgruhperuhgp this is your bucket name on the S3 server
    prefix: 'user-exports'
    base_url: ''

  # Same settings but for original video files
  original_video_files:
    bucket_name:  'Unique_bucket_name' # e.g. iodfgphgfehpgruhperuhgp this is your bucket name on the S3 server
    prefix: 'original-video-files'
    base_url: ''

  # Video captions
  captions:
    bucket_name:  'Unique_bucket_name' # e.g. iodfgphgfehpgruhperuhgp this is your bucket name on the S3 server
    prefix: 'caption/'
    base_url: ''
```

**Comment by spirillen** [comment]
The reversed actions are also failing...

move-to-file-system

<details><summary>Details</summary>
<p>

```log
Job: 6
Type: move-to-file-system
Processed on 5/5/25, 8:17:52.219 PM
Finished on 5/5/25, 8:17:52.286 PM

{
  "videoUUID": "4f0d2f34-78a6-40c1-b9f1-daa022feef14",
  "isNewVideo": false,
  "previousVideoState": 8
}

NoSuchKey: The specified key does not exist.
    at de_NoSuchKeyRes (/var/www/peertube/versions/peertube-v7.1.1/node_modules/@aws-sdk/client-s3/dist-cjs/index.js:5032:21)
    at de_CommandError (/var/www/peertube/versions/peertube-v7.1.1/node_modules/@aws-sdk/client-s3/dist-cjs/index.js:4931:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /var/www/peertube/versions/peertube-v7.1.1/node_modules/@smithy/middleware-serde/dist-cjs/index.js:35:20
    at async /var/www/peertube/versions/peertube-v7.1.1/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:484:18
    at async /var/www/peertube/versions/peertube-v7.1.1/node_modules/@smithy/middleware-retry/dist-cjs/index.js:320:38
    at async /var/www/peertube/versions/peertube-v7.1.1/node_modules/@aws-sdk/middleware-flexible-checksums/dist-cjs/index.js:318:18
    at async /var/www/peertube/versions/peertube-v7.1.1/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:110:22
    at async /var/www/peertube/versions/peertube-v7.1.1/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:137:14
    at async /var/www/peertube/versions/peertube-v7.1.1/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:33:22
    at async makeAvailable (file:///var/www/peertube/versions/peertube-v7.1.1/dist/core/lib/object-storage/object-storage-helpers.js:120:22)
    at async makeHLSFileAvailable (file:///var/www/peertube/versions/peertube-v7.1.1/dist/core/lib/object-storage/videos.js:98:5)
    at async moveHLSFiles (file:///var/www/peertube/versions/peertube-v7.1.1/dist/core/lib/job-queue/handlers/move-to-file-system.js:83:13)
    at async moveVideoToStorageJob (file:///var/www/peertube/versions/peertube-v7.1.1/dist/core/lib/job-queue/handlers/shared/move-video.js:30:13)
    at async Object.processMoveToFileSystem [as move-to-file-system] (file:///var/www/peertube/versions/peertube-v7.1.1/dist/core/lib/job-queue/handlers/move-to-file-system.js:17:9)
    at async Object.wrapPromiseFun (file:///var/www/peertube/versions/peertube-v7.1.1/dist/core/lib/plugins/hooks.js:8:24)
```


```log
Job: 7
Type: move-to-file-system
Processed on 5/5/25, 8:17:52.286 PM
Finished on 5/5/25, 8:17:52.332 PM

{
  "videoUUID": "172aca61-019b-4dff-8930-89eada41cf1f",
  "isNewVideo": false,
  "previousVideoState": 1
}

NoSuchKey: The specified key does not exist.
    at de_NoSuchKeyRes (/var/www/peertube/versions/peertube-v7.1.1/node_modules/@aws-sdk/client-s3/dist-cjs/index.js:5032:21)
    at de_CommandError (/var/www/peertube/versions/peertube-v7.1.1/node_modules/@aws-sdk/client-s3/dist-cjs/index.js:4931:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /var/www/peertube/versions/peertube-v7.1.1/node_modules/@smithy/middleware-serde/dist-cjs/index.js:35:20
    at async /var/www/peertube/versions/peertube-v7.1.1/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:484:18
    at async /var/www/peertube/versions/peertube-v7.1.1/node_modules/@smithy/middleware-retry/dist-cjs/index.js:320:38
    at async /var/www/peertube/versions/peertube-v7.1.1/node_modules/@aws-sdk/middleware-flexible-checksums/dist-cjs/index.js:318:18
    at async /var/www/peertube/versions/peertube-v7.1.1/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:110:22
    at async /var/www/peertube/versions/peertube-v7.1.1/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:137:14
    at async /var/www/peertube/versions/peertube-v7.1.1/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:33:22
    at async makeAvailable (file:///var/www/peertube/versions/peertube-v7.1.1/dist/core/lib/object-storage/object-storage-helpers.js:120:22)
    at async makeHLSFileAvailable (file:///var/www/peertube/versions/peertube-v7.1.1/dist/core/lib/object-storage/videos.js:98:5)
    at async moveHLSFiles (file:///var/www/peertube/versions/peertube-v7.1.1/dist/core/lib/job-queue/handlers/move-to-file-system.js:83:13)
    at async moveVideoToStorageJob (file:///var/www/peertube/versions/peertube-v7.1.1/dist/core/lib/job-queue/handlers/shared/move-video.js:30:13)
    at async Object.processMoveToFileSystem [as move-to-file-system] (file:///var/www/peertube/versions/peertube-v7.1.1/dist/core/lib/job-queue/handlers/move-to-file-system.js:17:9)
    at async Object.wrapPromiseFun (file:///var/www/peertube/versions/peertube-v7.1.1/dist/core/lib/plugins/hooks.js:8:24)
```



</p>
</details>

**Comment by Chocobozzz** [comment]
Hello,

Please can you detail what can be improved in the documentation. I don't understand your issue

**Comment by sij-ai** [comment]
I ran into this same issue migrating videos to Storj.io; this config fixed it for me:

```
object_storage:
  enabled: true
  endpoint: 'gateway.storjshare.io'
  region: 'us-east-1'
  credentials:
    access_key_id: 'ACCESS_KEY'
    secret_access_key: SECRET_KEY'
  upload_acl:
    public: 'public-read'
  proxy:
    proxify_private_files: true
  max_upload_part: 200MB
  max_request_attempts: 3

  streaming_playlists:
    bucket_name: 'web-videos'
    prefix: 'streaming-playlists/'
    base_url: 'https://link.storjshare.io/raw/LINK_SHARING_KEY/BUCKET_NAME'
    store_live_streams: false

  web_videos: # For progressive download .mp4 files
    bucket_name: 'web-videos'
    prefix: 'web-videos/'
    base_url: 'https://link.storjshare.io/raw/LINK_SHARING_KEY/BUCKET_NAME'

  captions: # For .vtt files
    bucket_name: 'web-videos'
    prefix: 'captions/'
    base_url: 'https://link.storjshare.io/raw/LINK_SHARING_KEY/BUCKET_NAME'

  user_exports:
    bucket_name: 'web-videos'
    prefix: 'user-exports/'
    base_url: 'https://link.storjshare.io/raw/LINK_SHARING_KEY/BUCKET_NAME'

  original_video_files: # If you keep originals and want a way to link them
    bucket_name: 'web-videos'
    prefix: 'original-video-files/'
    base_url: 'https://link.storjshare.io/raw/LINK_SHARING_KEY/BUCKET_NAME'
```

For this to work, you must make the bucket publicly accessible, e.g., via: 

```
uplink share --url --readonly --disallow-lists --not-after=none sj://BUCKET_NAME
```

Now that it's finally working, I will say, Storj is a great match for Peertube. The decentralized architecture fits, and means upload and playback speeds are super quick worldwide.

**Comment by spirillen** [comment]
Just a short follow up, as the chain of failures are multiply for why all of this went wrong and I'm still trying to recover from it.

The short version and headlines are:

1. Their is a first time for everything, I have never tried using S3 buckets before
2. The upload script to not check for successful file moving, it simply just assumes of success
     1. This leads to the false values of state (2|8) in the `video` table in the db
3. You are unable to successfully re-add the videos by using `create-import-video-file-job` as the video conversion are not taking place
4. the move script AND the converter suffers from not updating all table in the database after successful video re-conversion (state = 8) and their might be a similar value in other tables I have not found nor looked for.
5. When video.state = (2|8), you can not upload a new video version, to restart the "import" process, to correct any issues and thereby just start all over. Updating the video source rather than just delete the old post and create a new one is related to keeping url's
6. Handling of re-(aupload|convert|move-to-object) happens to fail a hole lot on bigger files (this one is in source about ~24GB)

I have for sure forgotten a lot of small details, but as my caterer is coming into play now, I stop for now, just please ask

The example @sij-ai have provided, are a good example for what I was trying to say earlier.

**Comment by spirillen** [comment]
And here is just an example of stalled values and 'hanging' processes that are all done and finished; however, the values in the database are not updated accordingly, forcing a 16-hour re-encoding of this ~24GB video. The most annoying part is that it only seems to work the first time (PeerTube version 6.x).

![Image](https://github.com/user-attachments/assets/c0b1a5b6-417c-4b3e-8dd4-5a58c459308c)

**Comment by Chocobozzz** [comment]
I'm really sorry but I still don't understand the precise problem. Please fill the [bug template](https://github.com/Chocobozzz/PeerTube/blob/develop/.github/ISSUE_TEMPLATE/00-bug-issue.md) and provide reproduce steps so I can find the root cause of your issues

**Comment by spirillen** [comment]
> I'm really sorry but I still don't understand the precise problem. Please fill the [bug template](https://github.com/Chocobozzz/PeerTube/blob/develop/.github/ISSUE_TEMPLATE/00-bug-issue.md) and provide steps to reproduce so I can find the root cause of your issues

I wouldn't expect to at this point, as said, I only replied with headlines.

My intention is to make a full step by step, describing where and in some cases how the entire transformation went wrong. So now you have some headlines, the full story is to be written, and that one will be beyond the issue template.

**Comment by spirillen** [comment]
Ok the short answer to the original question, how to optimise the docs.

I guessing that a short text that is making it clear that the `bucket_name:` means the literal "bucket name" of the S3 bucket, why, because you unlike other software, and tis is priceless, offer and support a bucket for each container type.

The current documentation got me of track, because the example got me to think in sub_path to the S3-bucket I've created.

A couple of other thought about the S3, is it possible to

1. Create a place to share how to setup the config in combination with the various S3 hosting platforms out there, shared knowledge is usual positive power
2. use S3 or other shared store for the cached contents? this will reduce the space requirement on the machine running Peertube.

And then, I still don't get this variable: 

```yml
  streaming_playlists:
    bucket_name: 'somerandomename'

    # Allows setting all buckets to the same value but with a different prefix
    prefix: ''
```
