### ISSUE TITLE
Peertube crash where login containt upercase or special char

### ISSUE THREAD

**Issue by Dryusdan** [Chocobozzz/PeerTube#81]
Hello
Actually, when I try to login, server crash when I tip an uppercase later or special char (an email adresse)

Regard :)

Sdtoud log
```
debug: [peertube.drycat.fr:443] Getting User (username: Dryusdan, password: personal).
debug: [peertube.drycat.fr:443] Executing (default): SELECT "id", "password", "username", "email", "displayNSFW", "role", "createdAt", "updatedAt" FROM "Users" AS "User" WHERE "User"."username" = 'Dryusdan' LIMIT 1;
Segmentation fault (core dumped)

npm info lifecycle peertube@0.0.1~start: Failed to exec start script
npm ERR! Linux 4.9.26-xxxx-std-ipv6-64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! peertube@0.0.1 start: `node dist/server`
npm ERR! Exit status 139
npm ERR!
npm ERR! Failed at the peertube@0.0.1 start script 'node dist/server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the peertube package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node dist/server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs peertube
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls peertube
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /PeerTube/npm-debug.log
```

**Comment by Chocobozzz** [comment]
Maybe a native dependency compiled with a previous node version?

Try `rm ./node_modules && yarn install --pure-lockfile` to reinstall your modules.

**Comment by Dryusdan** [comment]
It's a pur install with no cache (Dockerfile)

**Comment by Chocobozzz** [comment]
Can you share the Dockerfile so I can reproduce your issue?

**Comment by Dryusdan** [comment]
Here :) 
https://git.drycat.fr/Dryusdan/Dockerfiles/src/master/peertube

**Comment by Chocobozzz** [comment]
And your CLI to run it (or docker-compose...)? I suppose you use a PostgreSQL image

**Comment by Dryusdan** [comment]
Yes, postgresql with latest-alpine tag :) 

```
version: "3"

services:
  reverse-proxy:
    restart: always
    image: xataz/reverse-nginx
    container_name: reverse-proxy
    volumes:
      - /home/docker/reverse-proxy/ssl:/nginx/ssl
      - /home/docker/reverse-proxy/custom_sites:/nginx/custom_sites
      - /home/docker/reverse-proxy/log:/nginx/log
      - /home/docker/reverse-proxy/conf/nginx.conf:/nginx/conf/nginx.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - EMAIL=contact@dryusdan.fr
    ports:
      - "443:8443"
      - "80:8080"
    networks:
      front:
        ipv4_address: 172.20.1.1
  peertube:
    image: registry.tld/dryusdan/peertube
    container_name: peertube
    restart: always
    depends_on:
      - peertube-db
    environment:
      - HTTPS=true
      - HOSTNAME=peertube.drycat.fr
      - PORT=443
      - DATABASE_HOST=172.20.1.108
      - DATABASE_USERNAME=peertube
      - DATABASE_PASSWORD=z95U86mWLkKP4hj6
      - ADMIN_EMAIL=admin@drycat.fr
      - SIGNUP_ENABLE=true
      - TRANSCODING_THREADS=2
      - BODY_SIZE=1G
    labels:
      - reverse.frontend.domain=peertube.drycat.fr
      - reverse.frontend.path=/
      - reverse.backend.port=8080
      - reverse.frontend.domain_max_body_size=1G
      - reverse.frontend.ssl=true
    volumes:
      - /home/docker/web/drycat.fr/peertube/certs:/PeerTube/certs
      - /home/docker/web/drycat.fr/peertube/videos:/PeerTube/videos
      - /home/docker/web/drycat.fr/peertube/logs:/PeerTube/logs
      - /home/docker/web/drycat.fr/peertube/previews:/PeerTube/previews
      - /home/docker/web/drycat.fr/peertube/thumbnails:/PeerTube/thumbnails
      - /home/docker/web/drycat.fr/peertube/torrents:/PeerTube/torrents
      - /etc/localtime:/etc/localtime:ro
    networks:
      front:
        ipv4_address: 172.20.1.37
  peertube-db:
    restart: always
    container_name: peertube-postgresql
    image: postgres:alpine
    volumes:
      - /home/docker/db/peertube/postgresql/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      front:
        ipv4_address: 172.20.1.108
networks:
  front:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.1.0/16
```
