### ISSUE TITLE
Redis UNIX socket / configuration checker bug.

### ISSUE THREAD

**Issue by Bumbadawg** [Chocobozzz/PeerTube#840]
* **PeerTube version or URL:** peertube@1.0.0-beta.9
* **NodeJS version:** v10.7.0

* **What is the expected behaviour?** Redis Unix socket being used.
Excerpt from my configuration:
```
# Redis server for short time storage
redis:
   #hostname: 'localhost'
   #port: 6379
   socket: '/var/run/redis/redis.sock'
   auth: null
   db: 0
```
`
* **What do you see instead?** It was looking for Redis hostname although documentation asks to comment out.

* **Server log if useful (Gist/Pastebin...):** https://gist.github.com/Bumbadawg/5bdfa205635c4f1c7480d6c80fd9f210
